### ISSUE TITLE
SIGABRT due to double corrupted linked list in init_agent_snmp_session() malloc in net-snmp V5.8

### ISSUE THREAD

**Issue by Umakumar01** [net-snmp/net-snmp#109]
Please find the backtrace for the issue. Could anyone please let me know if you have overcome this issue
**BT**

Core was generated by `/usr/sbin/snmpd -C -c /tmp/snmpd.conf -Dtsm,dtls,openssl,cert,tls -f -a -Lo -I'.
~~~
Program terminated with signal 6, Aborted.
#0  __GI_raise (sig=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
#0  __GI_raise (sig=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
#1  0x76d61550 in __GI_abort () at /usr/src/debug/glibc/2.24-r0/git/stdlib/abort.c:89
#2  0x76d9956c in __libc_message (do_abort=2, fmt=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/posix/libc_fatal.c:175
#3  0x76da0c94 in malloc_printerr (action=3, str=0x76e64084 "corrupted double-linked list", ptr=0x57d420, ar_ptr=0x76e88714 <main_arena>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:5046
#4  0x76da3a48 in _int_malloc (av=0x76e88714 <main_arena>, bytes=12) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3762
#5  0x76da5c1c in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3271
#6  0x77245abc in init_agent_snmp_session (session=0x510ee0, pdu=0x595468) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:1587
#7  0x7724ab70 in handle_snmp_packet (op=1, session=<optimized out>, reqid=<optimized out>, pdu=0x595468, magic=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:2211
#8  0x76ed0ed0 in _sess_process_packet_handle_pdu (transport=0x510d30, pdu=0x595468, isp=0x504a50, sp=0x510ee0, sessp=0x586190) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5804
#9  _sess_process_packet (sessp=0x586190, sp=0x510ee0, isp=0x504a50, transport=0x510d30, opaque=0x586190, olength=60, packetptr=0x512e98 "02\002\001\001\004\bhDaFHJG7\241#\002\004~\342H\332\002\001", length=52) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5860
#10 0x76ed2348 in _sess_read (sessp=0x4ff4b0, fdset=0x7ffef6c0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6121
#11 0x76ed2388 in snmp_sess_read2 (sessp=0x4ff4b0, fdset=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6405
#12 0x76ed2420 in snmp_read2 (fdset=0x7ffef6c0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5909
#13 0x00403f48 in receive () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1342
#14 0x00402f6c in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1125

BT FULL

Core was generated by `/usr/sbin/snmpd -C -c /tmp/snmpd.conf -Dtsm,dtls,openssl,cert,tls -f -a -Lo -I'.
Program terminated with signal 6, Aborted.
#0  __GI_raise (sig=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
#0  __GI_raise (sig=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
set = {__val = {0, 0, 0, 0, 5857260, 2147414000, 2147413976, 1995266408, 15, 1995352876, 1995759616, 1995354300, 1995900208, 2147415144, 1995900208, 5320377, 1994984960, 5854312, 2147415144, 5857260, 1995694080, 5320396, 2147414040, 1995352876, 1994481040, 1993987232, 1994989568, 1994989568, 1994958596, 2147414256, 2, 1}}
err = <optimized out>
pid = <optimized out>
tid = <optimized out>
ret = 0
#1  0x76d61550 in __GI_abort () at /usr/src/debug/glibc/2.24-r0/git/stdlib/abort.c:89
save_stage = 2
act = {sa_flags = 0, __sigaction_handler = {sa_handler = 0x512ecc, sa_sigaction = 0x512ecc}, sa_mask = {__val = {2147414128, 1995232960, 1993649484, 5854494, 1995719119, 4278124287, 4704, 2147414688, 2147415144, 0, 1995900208, 0, 1, 3, 6, 1, 4, 1, 17270, 9225, 2, 1, 9, 1, 2, 4294967295, 1, 10, 2147414296, 1994018732, 1, 10}}, sa_restorer = 0x7ffef128, sa_resv = {1994018732}}
sigs = {__val = {32, 0 <repeats 31 times>}}
#2  0x76d9956c in __libc_message (do_abort=2, fmt=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/posix/libc_fatal.c:175
ap = 0x7ffef2dc
fd = 2
on_2 = <optimized out>
list = <optimized out>
nlist = 7
cp = <optimized out>
written = true
#3  0x76da0c94 in malloc_printerr (action=3, str=0x76e64084 "corrupted double-linked list", ptr=0x57d420, ar_ptr=0x76e88714 <main_arena>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:5046
buf = "0057d420"
cp = <optimized out>
ar_ptr = 0x76e88714 <main_arena>
ptr = 0x57d420
str = 0x76e64084 "corrupted double-linked list"
action = 3
#4  0x76da3a48 in _int_malloc (av=0x76e88714 <main_arena>, bytes=12) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3762
iters = <optimized out>
nb = 16
idx = <optimized out>
bin = <optimized out>
victim = 0x57d420
size = 32
victim_index = <optimized out>
remainder = <optimized out>
remainder_size = 16
block = <optimized out>
bit = <optimized out>
map = <optimized out>
fwd = 0x57d420
bck = <optimized out>
errstr = 0x0
__func__ = "_int_malloc"
#5  0x76da5c1c in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3271
av = 0x76e88714 <main_arena>
oldtop = 0x5966c8
p = <optimized out>
bytes = 12
sz = 12
csz = <optimized out>
oldtopsize = 117048
mem = <optimized out>
clearsize = <optimized out>
nclears = <optimized out>
d = <optimized out>
hook = <optimized out>
__func__ = "__libc_calloc"
#6  0x77245abc in init_agent_snmp_session (session=0x510ee0, pdu=0x595468) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:1587
asp = 0x5948f0
__func__ = "init_agent_snmp_session"
#7  0x7724ab70 in handle_snmp_packet (op=1, session=<optimized out>, reqid=<optimized out>, pdu=0x595468, magic=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:2211
status = <optimized out>
access_ret = <optimized out>
asp = <optimized out>
rc = <optimized out>
reqid = <optimized out>
magic = 0x0
pdu = 0x595468
op = 1
session = <optimized out>
#8  0x76ed0ed0 in _sess_process_packet_handle_pdu (transport=0x510d30, pdu=0x595468, isp=0x504a50, sp=0x510ee0, sessp=0x586190) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5804
slp = 0x586190
rp = <optimized out>
orp = 0x0
handled = 1
#9  _sess_process_packet (sessp=0x586190, sp=0x510ee0, isp=0x504a50, transport=0x510d30, opaque=0x586190, olength=60, packetptr=0x512e98 "02\002\001\001\004\bhDaFHJG7\241#\002\004~\342H\332\002\001", length=52) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5860
slp = 0x4ff4b0
__func__ = "_sess_process_packet"
#10 0x76ed2348 in _sess_read (sessp=0x4ff4b0, fdset=0x7ffef6c0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6121
rcvp = {packet = 0x512e98 "02\002\001\001\004\bhDaFHJG7\241#\002\004~\342H\332\002\001", packet_len = 52, opaque = 0x586190, olength = 60}
slp = 0x4ff4b0
sp = <optimized out>
isp = <optimized out>
transport = 0x510d30
pdulen = 0
rxbuf_len = 65536
rxbuf = 0x0
length = 0
olength = 0
rc = <optimized out>
opaque = 0x0
__func__ = "_sess_read"
__FUNCTION__ = "_sess_read"
#11 0x76ed2388 in snmp_sess_read2 (sessp=0x4ff4b0, fdset=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6405
psl = <optimized out>
pss = <optimized out>
rc = 0
#12 0x76ed2420 in snmp_read2 (fdset=0x7ffef6c0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5909
slp = 0x4ff4b0
#13 0x00403f48 in receive () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1342
numfds = 17
readfds = {lfs_setsize = 1024, lfs_setptr = 0x7ffef6c8, lfs_set = {fds_bits = {0 <repeats 32 times>}}}
writefds = {lfs_setsize = 1024, lfs_setptr = 0x7ffef640, lfs_set = {fds_bits = {0 <repeats 32 times>}}}
exceptfds = {lfs_setsize = 1024, lfs_setptr = 0x7ffef5b8, lfs_set = {fds_bits = {0 <repeats 32 times>}}}
timeout = {tv_sec = 1, tv_usec = 636550}
tvp = 0x7ffef748
count = 1
block = 0
i = <optimized out>
__func__ = "receive"
#14 0x00402f6c in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1125
options = "aAc:CdD::fhHI:l:L:m:M:n:p:P:qrsS:UvV-:Y:g:u:x:X"
arg = <optimized out>
i = <optimized out>
ret = <optimized out>
exit_code = 1
dont_fork = <optimized out>
do_help = <optimized out>
log_set = <optimized out>
agent_mode = <optimized out>
pid_file = 0x0
option_compatability = "-Le"
prepared_sockets = 8388608
fd = <optimized out>
PID = <optimized out>
__func__ = "main"

THREAD APPLY ALL BT

Core was generated by `/usr/sbin/snmpd -C -c /tmp/snmpd.conf -Dtsm,dtls,openssl,cert,tls -f -a -Lo -I'.
Program terminated with signal 6, Aborted.
#0  __GI_raise (sig=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58

Thread 1 (LWP 2042):
#0  __GI_raise (sig=6) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/raise.c:58
#1  0x76d61550 in __GI_abort () at /usr/src/debug/glibc/2.24-r0/git/stdlib/abort.c:89
#2  0x76d9956c in __libc_message (do_abort=2, fmt=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/sysdeps/posix/libc_fatal.c:175
#3  0x76da0c94 in malloc_printerr (action=3, str=0x76e64084 "corrupted double-linked list", ptr=0x57d420, ar_ptr=0x76e88714 <main_arena>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:5046
#4  0x76da3a48 in _int_malloc (av=0x76e88714 <main_arena>, bytes=12) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3762
#5  0x76da5c1c in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3271
#6  0x77245abc in init_agent_snmp_session (session=0x510ee0, pdu=0x595468) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:1587
#7  0x7724ab70 in handle_snmp_packet (op=1, session=<optimized out>, reqid=<optimized out>, pdu=0x595468, magic=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:2211
#8  0x76ed0ed0 in _sess_process_packet_handle_pdu (transport=0x510d30, pdu=0x595468, isp=0x504a50, sp=0x510ee0, sessp=0x586190) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5804
#9  _sess_process_packet (sessp=0x586190, sp=0x510ee0, isp=0x504a50, transport=0x510d30, opaque=0x586190, olength=60, packetptr=0x512e98 "02\002\001\001\004\bhDaFHJG7\241#\002\004~\342H\332\002\001", length=52) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5860
#10 0x76ed2348 in _sess_read (sessp=0x4ff4b0, fdset=0x7ffef6c0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6121
#11 0x76ed2388 in snmp_sess_read2 (sessp=0x4ff4b0, fdset=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6405
#12 0x76ed2420 in snmp_read2 (fdset=0x7ffef6c0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5909
#13 0x00403f48 in receive () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1342
#14 0x00402f6c in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1125
~~~

**Comment by bvanassche** [comment]
If this happened with the official v5.8 release, please verify whether this still occurs with the latest code from the V5-8-patches branch (https://github.com/net-snmp/net-snmp/archive/V5-8-patches.zip).

**Comment by bvanassche** [comment]
Please reopen this issue if it needs further attention.
