### ISSUE TITLE
net-snmp snmpd demon is getting crashed "Core was generated by `snmpd -f -c /cfs/system/snmpd.conf'"

### ISSUE THREAD

**Issue by AmitSharma1094** [net-snmp/net-snmp#11]
Core was generated by `snmpd -f -c /cfs/system/snmpd.conf' 

I am using net-snmp 5.8 as version and crashed observed after 30 min fo snmp query
bt result:-
~~~
Program terminated with signal SIGABRT, Aborted.
#0  0xf7abfb47 in raise () from /lib/libc.so.6
(gdb) bt
#0  0xf7abfb47 in raise () from /lib/libc.so.6
#1  0xf7ac0cd9 in abort () from /lib/libc.so.6
#2  0xf7affa6b in ?? () from /lib/libc.so.6
#3  0xf7b0649d in ?? () from /lib/libc.so.6
#4  0xf7b07e09 in ?? () from /lib/libc.so.6
#5  0xf7d1033d in usm_free_usmStateReference () from /lib/libnetsnmp.so.35
#6  0xf7d1208e in usm_generate_out_msg () from /lib/libnetsnmp.so.35
#7  0xf7d1216d in usm_secmod_generate_out_msg () from /lib/libnetsnmp.so.35
#8  0xf7cf07f1 in snmpv3_packet_build () from /lib/libnetsnmp.so.35
#9  0xf7cf0bab in snmp_build () from /lib/libnetsnmp.so.35
#10 0xf7cf0fa3 in netsnmp_build_packet () from /lib/libnetsnmp.so.35
#11 0xf7cf11d9 in _build_initial_pdu_packet () from /lib/libnetsnmp.so.35
#12 0xf7ed32f1 in netsnmp_wrap_up_request () from /lib/libnetsnmpagent.so.35
#13 0xf7ed4791 in netsnmp_handle_request () from /lib/libnetsnmpagent.so.35
#14 0xf7ed48d3 in handle_snmp_packet () from /lib/libnetsnmpagent.so.35
#15 0xf7cf51f2 in ?? () from /lib/libnetsnmp.so.35
#16 0xf7cf58fc in _sess_read () from /lib/libnetsnmp.so.35
#17 0xf7cf593b in snmp_sess_read2 () from /lib/libnetsnmp.so.35
#18 0xf7cf5982 in snmp_read2 () from /lib/libnetsnmp.so.35
#19 0x0804ac1b in ?? ()
#20 0x0804a6ed in ?? ()
#21 0xf7aabe41 in __libc_start_main () from /lib/libc.so.6
#22 0x0804a7d5 in ?? ()
~~~

**Comment by bvanassche** [comment]
This is a known bug in version v5.8. Please retest with the latest version of the v5.8 branch. A zip file for the v5.8 branch is available at https://github.com/net-snmp/net-snmp/archive/V5-8-patches.zip .

**Comment by krishnacx** [comment]
> This is a known bug in version v5.8. Please retest with the latest version of the v5.8 branch. A zip file for the v5.8 branch is available at https://github.com/net-snmp/net-snmp/archive/V5-8-patches.zip .

@bvanassche Can you provide the commit id(s) for checking the diff
