### ISSUE TITLE
SNMP stopped running all of sudden - double free or corruption

### ISSUE THREAD

**Issue by kulhar** [net-snmp/net-snmp#112]
Version - snmpd 5.8+dfsg-2 "double free or corruption"
Also giving warnings for all valid configuration like defaultMonitors, linkUpDownNotifications and 
_mteTTable.

openat(AT_FDCWD, "/proc/net/ipv6_route", O_RDONLY) = 14
fstat(14, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
read(14, "fe800000000000000000000000000000"..., 1024) = 900
read(14, "", 1024) = 0
close(14) = 0
clock_gettime(CLOCK_MONOTONIC, {501384, 839231761}) = 0
clock_gettime(CLOCK_MONOTONIC, {501384, 839412979}) = 0
writev(2, [
{"*double free or corruption* (fastt"..., 35}

, {"\n", 1}], 2) = 36
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39a2e10000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid() = 17928
gettid() = 17928
tgkill(17928, 17928, SIGABRT) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0

                SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=17928, si_uid=111} ---*
                +++ killed by SIGABRT +++

Apr 30 19:39:11 snmpd[1895]: Cannot adopt OID in UCD-SNMP-MIB: laIndex ::= { laEntry 1 }
Apr 30 19:39:11 snmpd[1895]: /etc/snmp/snmpd.conf: line 157: Warning: Unknown token: defaultMonitors.
Apr 30 19:39:11 snmpd[1895]: /etc/snmp/snmpd.conf: line 160: Warning: Unknown token: linkUpDownNotifications.
Apr 30 19:39:11 snmpd[1895]: /var/lib/snmp/snmpd.conf: line 34: Warning: Unknown token: _mteTTable.
Apr 30 19:39:11 snmpd[1895]: /var/lib/snmp/snmpd.conf: line 35: Warning: Unknown token: _mteTTable.
Apr 30 19:39:11 snmpd[1895]: /var/lib/snmp/snmpd.conf: line 36: Warning: Unknown token: _mteTTable.
Apr 30 19:39:11 snmpd[1895]: /var/lib/snmp/snmpd.conf: line 37: Warning: Unknown token: _mteTTable.
Apr 30 19:39:11 snmpd[1895]: /var/lib/snmp/snmpd.conf: line 38: Warning: Unknown token: _mteTTable.
Apr 30 19:39:11 snmpd[1895]: /var/lib/snmp/snmpd.conf: line 39: Warning: Unknown token: _mteTTable.
Apr 30 19:39:11 snmpd[1895]: /var/lib/snmp/snmpd.conf: line 40: Warning: Unknown token: _mteTTable.
Apr 30 19:39:11 snmpd[1895]: Error opening specified endpoint "udp:161"
Apr 30 19:39:11 snmpd[1895]: Server Exiting with code 1

**Comment by bvanassche** [comment]
Is this easy to reproduce? If so, please reproduce this with snmpd running under Valgrind and provide the Valgrind output.

**Comment by kulhar** [comment]
Yes, it is reproducible in my setup, I will provide the Valgrind output.
Why SNMP is giving warnings for defaultMonitors, linkUpDownNotifications and
_mteTTable ? 
 defaultMonitors, linkUpDownNotifications, _mteTTable all are valid tags.

**Comment by bvanassche** [comment]
The defaultMonitors, linkUpDownNotifications and _mteTTable keywords are only recognized if the DISMAN MIB has been loaded. Maybe that MIB has not been loaded or has been disabled on your setup?

**Comment by kulhar** [comment]
Command : /usr/sbin/snmpd -LSwd -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux mteTrigger mteTriggerConf -p /run/snmpd.pid


gdb /usr/sbin/snmpd core-snmpd 
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/snmpd...(no debugging symbols found)...done.
[New LWP 2101]
BFD: /usr/lib/debug/.build-id/5e/7bd9d721902e436445247472e5f91a149b3faa.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/5e/7bd9d721902e436445247472e5f91a149b3faa.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/5e/7bd9d721902e436445247472e5f91a149b3faa.debug" has no build-id, file skipped
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
BFD: /usr/lib/debug/.build-id/14/1885029bf0c40ea55ae3b56651d085c856fb0b.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/14/1885029bf0c40ea55ae3b56651d085c856fb0b.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/14/1885029bf0c40ea55ae3b56651d085c856fb0b.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/bd/c4116b3193146db4945c36329513df492b14ab.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/bd/c4116b3193146db4945c36329513df492b14ab.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/bd/c4116b3193146db4945c36329513df492b14ab.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/5b/bc8399ac25a58b1973d064e171e437c856d69b.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/5b/bc8399ac25a58b1973d064e171e437c856d69b.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/5b/bc8399ac25a58b1973d064e171e437c856d69b.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/8c/26d6884ef21137fe6f976f5679e5e172ae43fe.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/8c/26d6884ef21137fe6f976f5679e5e172ae43fe.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/8c/26d6884ef21137fe6f976f5679e5e172ae43fe.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/e4/970c89bd004ce0922d937642bbb3db7226a80f.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/e4/970c89bd004ce0922d937642bbb3db7226a80f.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/e4/970c89bd004ce0922d937642bbb3db7226a80f.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/c0/5e9583d6e75b775fe46b97e70bc0453feee036.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/c0/5e9583d6e75b775fe46b97e70bc0453feee036.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/c0/5e9583d6e75b775fe46b97e70bc0453feee036.debug" has no build-id, file skipped
BFD: /usr/lib/debug/.build-id/ee/5900419b8dbc03a48c8642676625a2bcd35913.debug: unable to initialize decompress status for section .debug_aranges
BFD: /usr/lib/debug/.build-id/ee/5900419b8dbc03a48c8642676625a2bcd35913.debug: unable to initialize decompress status for section .debug_aranges

warning: File "/usr/lib/debug/.build-id/ee/5900419b8dbc03a48c8642676625a2bcd35913.debug" has no build-id, file skipped
Core was generated by `/usr/sbin/snmpd'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f4d7e343081 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f4d7e343081 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f4d7e32e535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f4d7e384dc8 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f4d7e38b32a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f4d7e38cd74 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007f4d7e54ab80 in usm_free_usmStateReference () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#6  0x00007f4d7e54fec5 in usm_generate_out_msg () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#7  0x00007f4d7e550705 in usm_secmod_generate_out_msg () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#8  0x00007f4d7e506bc2 in snmpv3_packet_build () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#9  0x00007f4d7e508c07 in snmp_build () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#10 0x00007f4d7e50912b in netsnmp_build_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#11 0x00007f4d7e509347 in _build_initial_pdu_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#12 0x00007f4d7e91e808 in netsnmp_wrap_up_request () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.35
#13 0x00007f4d7e92196b in netsnmp_handle_request () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.35
#14 0x00007f4d7e921c9b in handle_snmp_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.35
#15 0x00007f4d7e51131f in ?? () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#16 0x00007f4d7e5123b6 in _sess_read () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#17 0x00007f4d7e512ee9 in snmp_sess_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#18 0x00007f4d7e512f3b in snmp_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
#19 0x000055a55ce4e5f2 in ?? ()
#20 0x000055a55ce4da89 in main ()
(gdb) bt full
#0  0x00007f4d7e343081 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f4d7e32e535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00007f4d7e384dc8 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#3  0x00007f4d7e38b32a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#4  0x00007f4d7e38cd74 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#5  0x00007f4d7e54ab80 in usm_free_usmStateReference () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#6  0x00007f4d7e54fec5 in usm_generate_out_msg () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#7  0x00007f4d7e550705 in usm_secmod_generate_out_msg () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#8  0x00007f4d7e506bc2 in snmpv3_packet_build () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#9  0x00007f4d7e508c07 in snmp_build () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#10 0x00007f4d7e50912b in netsnmp_build_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#11 0x00007f4d7e509347 in _build_initial_pdu_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#12 0x00007f4d7e91e808 in netsnmp_wrap_up_request () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.35
No symbol table info available.
#13 0x00007f4d7e92196b in netsnmp_handle_request () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.35
No symbol table info available.
#14 0x00007f4d7e921c9b in handle_snmp_packet () from /usr/lib/x86_64-linux-gnu/libnetsnmpagent.so.35
No symbol table info available.
#15 0x00007f4d7e51131f in ?? () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#16 0x00007f4d7e5123b6 in _sess_read () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#17 0x00007f4d7e512ee9 in snmp_sess_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#18 0x00007f4d7e512f3b in snmp_read2 () from /usr/lib/x86_64-linux-gnu/libnetsnmp.so.35
No symbol table info available.
#19 0x000055a55ce4e5f2 in ?? ()
No symbol table info available.
#20 0x000055a55ce4da89 in main ()
No symbol table info available.
(gdb)

**Comment by bvanassche** [comment]
Please repeat this test with the latest code from the v5.8 branch (https://github.com/net-snmp/net-snmp/archive/V5-8-patches.zip). A fix for the usm code was checked in about nine months ago. See also commit 5f881d3bf24599b90d67a45cae7a3eb099cd71c9.
