### ISSUE TITLE
SEGFAULT occurs when recon figuring  snmpd agent

### ISSUE THREAD

**Issue by Umakumar01** [net-snmp/net-snmp#127]

**Comment by Umakumar01** [comment]
SEGFAULT occurred in _map_fp_compare function in net-snmp version 5.8
We have configured SNMPv3 certs using file name like
certSecName 10 <crt file name> --cn 
certSecName 11 <crt file name> --cn 

after some time segmentation fault occurs in _map_fp_compare in strcmp of fingerprint. Adding NULL check doesnt resolve the issue. Looks like it is due invalid memory access. Could anyone please check

Code snippet: 

> static int
_map_fp_compare(netsnmp_cert_map *lhs, netsnmp_cert_map *rhs)
{
    int rc;
    netsnmp_assert((lhs != NULL) && (rhs != NULL));

    if ((rc = strcmp(lhs->fingerprint, rhs->fingerprint)) != 0)
        return rc;

    if (lhs->priority < rhs->priority)
        return -1;


BT:
`crashed_binary_name :  snmpd


BT

Core was generated by `/usr/sbin/snmpd -C -c /tmp/snmpd.conf -Dtsm,dtls,openssl,cert,tls -f -a -Lo -I'.
Program terminated with signal 11, Segmentation fault.
#0  strcmp () at ../sysdeps/mips/strcmp.S:103
#0  strcmp () at ../sysdeps/mips/strcmp.S:103
#1  0x7729a494 in _map_fp_compare (lhs=0x4b7008, rhs=0x505c78) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/cert_util.c:2560
#2  0x772df848 in binary_search (val=0x505c78, c=0x41d350, exact=1, next=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:184
#3  0x772e0e54 in netsnmp_binary_array_remove (c=0x41d350, key=0x505c78, save=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:411
#4  0x772e0ec4 in _ba_remove (container=<optimized out>, data=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:685
#5  0x772de730 in CONTAINER_REMOVE (x=0x41d350, k=0x505c78) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container.c:395
#6  0x7729f3b0 in _purge_config_entries () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/cert_util.c:2680
#7  0x7728d5e0 in free_config () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/read_config.c:1000
#8  0x775e16f8 in update_config () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_read_config.c:309
#9  0x773b4738 in update_hook (action=<optimized out>, var_val=<optimized out>, var_val_type=<optimized out>, var_val_len=<optimized out>, statP=0x774d409c <long_ret.11000> "", name=0x577ec0, name_len=10) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/mibgroup/ucd-snmp/versioninfo.c:178
#10 0x775cb01c in netsnmp_old_api_helper (handler=0x44da00, reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/helpers/old_api.c:424
#11 0x775ddc18 in netsnmp_call_handler (next_handler=0x44da00, reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_handler.c:546
#12 0x775ddff8 in netsnmp_call_handlers (reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_handler.c:631
#13 0x775f0f04 in handle_var_requests (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3001
#14 0x775f1b24 in handle_set (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3578
#15 0x775f1cc4 in handle_set_loop (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3594
#16 0x775f2404 in handle_pdu (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3857
#17 0x775f27cc in netsnmp_handle_request (asp=0x577330, status=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3676
#18 0x775f2e30 in netsnmp_check_outstanding_agent_requests () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3169
#19 0x00403f78 in receive () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1379
#20 0x00402f6c in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1125

BT FULL

Core was generated by `/usr/sbin/snmpd -C -c /tmp/snmpd.conf -Dtsm,dtls,openssl,cert,tls -f -a -Lo -I'.
Program terminated with signal 11, Segmentation fault.
#0  strcmp () at ../sysdeps/mips/strcmp.S:103
#0  strcmp () at ../sysdeps/mips/strcmp.S:103
No locals.
#1  0x7729a494 in _map_fp_compare (lhs=0x4b7008, rhs=0x505c78) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/cert_util.c:2560
rc = <optimized out>
#2  0x772df848 in binary_search (val=0x505c78, c=0x41d350, exact=1, next=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:184
t = 0x41d3c8
len = 1
half = 2146596304
first = 0
middle = 0
result = 0
#3  0x772e0e54 in netsnmp_binary_array_remove (c=0x41d350, key=0x505c78, save=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:411
t = <optimized out>
save = 0x0
key = 0x505c78
c = 0x41d350
t = <optimized out>
#4  0x772e0ec4 in _ba_remove (container=<optimized out>, data=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:685
No locals.
#5  0x772de730 in CONTAINER_REMOVE (x=0x41d350, k=0x505c78) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container.c:395
rc2 = <optimized out>
rc = 0
#6  0x7729f3b0 in _purge_config_entries () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/cert_util.c:2680
itr = 0x44e608
cert_map = 0x505c78
cert_maps = 0x41d2b0
tmp_maps = 0x577288
#7  0x7728d5e0 in free_config () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/read_config.c:1000
ctmp = 0x417480
ltmp = 0x41d290
#8  0x775e16f8 in update_config () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_read_config.c:309
No locals.
#9  0x773b4738 in update_hook (action=<optimized out>, var_val=<optimized out>, var_val_type=<optimized out>, var_val_len=<optimized out>, statP=0x774d409c <long_ret.11000> "", name=0x577ec0, name_len=10) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/mibgroup/ucd-snmp/versioninfo.c:178
var_val_len = <optimized out>
var_val = <optimized out>
action = <optimized out>
statP = 0xa <Address 0xa out of bounds>
name = 0x0
name_len = 2002986768
#10 0x775cb01c in netsnmp_old_api_helper (handler=0x44da00, reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/helpers/old_api.c:424
save = {1, 3, 6, 1, 4, 1, 2021, 100, 11, 0, 4294920, 255, 0, 0, 0, 1998818816, 0, 775238962, 774909488, 2146566192, 1997852588, 4515336, 5731584, 0, 1998391704, 1998818816, 110, 0, 119, 1999734064, 256, 4, 1999612256, 5285104, 1999593472, 1999593472, 1999593472, 2146597832, 1999186732, 1999734064, 4515360, 4, 1999612256, 5285104, 1999593472, 1999593472, 1999593472, 2146597872, 1999186732, 2146597880, 1999188156, 1999734064, 1999186732, 1999734064, 4278124287, 1999734064, 5731416, 1999568656, 2146598112, 2146597920, 1999147608, 2146597928, 2146597928, 1999612256, 4278124287, 495, 2002878464, 1999734064, 2002878464, 1668246538, 1985965153, 7824745, 5731416, 10, 2, 2146597984, 1999151428, 2146597992, 1731491339, 1999734064, 828322390, 5731416, 5285104, 2146598112, 5734080, 10, 0, 2146598032, 1999186732, 2146598040, 1999155608, 5731416, 2002878464, 1999734064, 5734080, 0, 0, 2002883352, 2002878464, 2146598080, 2002777428, 0, 0, 1, 4278124287, 1441, 2146598152, 2002986768, 0, 0, 0, 0, 0, 0, 0, 1999734064, 0, 4512256, 2002562044, 2002860680, 2002862724, 5731200, 2002878464, 1999734064, 1999186732, 1999734064, 2002562044, 4512256}
savelen = 10
compat_var = {magic = 11 '\v', type = 2 '\002', acl = 2, findVar = 0x773b4370 <var_extensible_version>, namelen = 9 '\t', name = {1, 3, 6, 1, 4, 1, 2021, 100, 11, 5202968, 0, 0, 1998921316, 0, 1999190312, 0, 5702164, 2146598172, 2146598168, 2146598224, 4513340, 4, 2146598232, 2146598240, 2146598236, 1, 4946936, 2146596768, 1998921316, 12, 2146597496, 2146597504, 2146597500, 2146598236, 2146598232, 1, 2146598224, 0, 2146598228, 1999734064, 2146598048, 5202968, 0, 0, 2146597488, 0, 1999190312, 1999734064, 0, 1, 1997661044, 2146598160, 4514192, 5, 2146598168, 2146598176, 2146598172, 5202968, 0, 0, 1998921316, 0, 1999190312, 0, 5702160, 2146598172, 2146598168, 2146598224, 4513336, 5, 2146598232, 2146598240, 2146598236, 1, 4946776, 2146596960, 1998921316, 0, 124, 1997835184, 2146597500, 2146598236, 2146598232, 1, 2146598224, 0, 2146598228, 1999734064, 0, 5202968, 0, 0, 1997852588, 0, 1999190312, 1999734064, 92, 1998818816, 110, 2146598160, 4514188, 6, 2146598168, 2146598176, 2146598172, 5202968, 0, 0, 1998921316, 0, 1999190312, 1999734064, 1997844804, 2146598172, 2146598168, 2146598224, 4513332, 6, 2146598232, 2146598240, 2146598236, 1, 4945800, 2146597152, 1998921316, 5894006, 826505960, 1}}
cvp = 0x7ff27758
exact = 2002639896
status = <optimized out>
vp = 0x44dce0
cacheptr = 0x452408
oldasp = 0x0
access = <optimized out>
write_method = 0x0
len = 2002860680
tmp_len = 2002562044
tmp_name = {1, 3, 6, 1, 4, 1, 2021, 100, 11, 0 <repeats 119 times>}
__func__ = "netsnmp_old_api_helper"
#11 0x775ddc18 in netsnmp_call_handler (next_handler=0x44da00, reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_handler.c:546
nh = 0x775cabfc <netsnmp_old_api_helper>
ret = <optimized out>
#12 0x775ddff8 in netsnmp_call_handlers (reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_handler.c:631
request = <optimized out>
status = 5246776
__func__ = "netsnmp_call_handlers"
#13 0x775f0f04 in handle_var_requests (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3001
i = 0
retstatus = <optimized out>
status = <optimized out>
final_status = 0
reginfo = <optimized out>
#14 0x775f1b24 in handle_set (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3578
status = <optimized out>
__func__ = "handle_set"
#15 0x775f1cc4 in handle_set_loop (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3594
No locals.
#16 0x775f2404 in handle_pdu (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3857
status = <optimized out>
inclusives = <optimized out>
v = <optimized out>
__func__ = "handle_pdu"
#17 0x775f27cc in netsnmp_handle_request (asp=0x577330, status=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3676
__func__ = "netsnmp_handle_request"
#18 0x775f2e30 in netsnmp_check_outstanding_agent_requests () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3169
asp = 0x577330
#19 0x00403f78 in receive () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1379
numfds = 16
readfds = {lfs_setsize = 1024, lfs_setptr = 0x7ff280e8, lfs_set = {fds_bits = {32768, 0 <repeats 31 times>}}}
writefds = {lfs_setsize = 1024, lfs_setptr = 0x7ff28060, lfs_set = {fds_bits = {0 <repeats 32 times>}}}
exceptfds = {lfs_setsize = 1024, lfs_setptr = 0x7ff27fd8, lfs_set = {fds_bits = {0 <repeats 32 times>}}}
timeout = {tv_sec = 0, tv_usec = 446863}
tvp = 0x7ff28168
count = 1
block = 0
i = <optimized out>
__func__ = "receive"
#20 0x00402f6c in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1125
options = "aAc:CdD::fhHI:l:L:m:M:n:p:P:qrsS:UvV-:Y:g:u:x:X"
arg = <optimized out>
i = <optimized out>
ret = <optimized out>
exit_code = 1
dont_fork = <optimized out>
do_help = <optimized out>
log_set = <optimized out>
agent_mode = <optimized out>
pid_file = 0x0
option_compatability = "-Le"
prepared_sockets = 8388608
fd = <optimized out>
PID = <optimized out>
__func__ = "main"

THREAD APPLY ALL BT

Core was generated by `/usr/sbin/snmpd -C -c /tmp/snmpd.conf -Dtsm,dtls,openssl,cert,tls -f -a -Lo -I'.
Program terminated with signal 11, Segmentation fault.
#0  strcmp () at ../sysdeps/mips/strcmp.S:103

Thread 1 (LWP 9582):
#0  strcmp () at ../sysdeps/mips/strcmp.S:103
#1  0x7729a494 in _map_fp_compare (lhs=0x4b7008, rhs=0x505c78) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/cert_util.c:2560
#2  0x772df848 in binary_search (val=0x505c78, c=0x41d350, exact=1, next=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:184
#3  0x772e0e54 in netsnmp_binary_array_remove (c=0x41d350, key=0x505c78, save=0x0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:411
#4  0x772e0ec4 in _ba_remove (container=<optimized out>, data=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container_binary_array.c:685
#5  0x772de730 in CONTAINER_REMOVE (x=0x41d350, k=0x505c78) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/container.c:395
#6  0x7729f3b0 in _purge_config_entries () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/cert_util.c:2680
#7  0x7728d5e0 in free_config () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/read_config.c:1000
#8  0x775e16f8 in update_config () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_read_config.c:309
#9  0x773b4738 in update_hook (action=<optimized out>, var_val=<optimized out>, var_val_type=<optimized out>, var_val_len=<optimized out>, statP=0x774d409c <long_ret.11000> "", name=0x577ec0, name_len=10) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/mibgroup/ucd-snmp/versioninfo.c:178
#10 0x775cb01c in netsnmp_old_api_helper (handler=0x44da00, reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/helpers/old_api.c:424
#11 0x775ddc18 in netsnmp_call_handler (next_handler=0x44da00, reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_handler.c:546
#12 0x775ddff8 in netsnmp_call_handlers (reginfo=0x44dca8, reqinfo=0x577380, requests=0x50ef70) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/agent_handler.c:631
#13 0x775f0f04 in handle_var_requests (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3001
#14 0x775f1b24 in handle_set (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3578
#15 0x775f1cc4 in handle_set_loop (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3594
#16 0x775f2404 in handle_pdu (asp=0x577330) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3857
#17 0x775f27cc in netsnmp_handle_request (asp=0x577330, status=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3676
#18 0x775f2e30 in netsnmp_check_outstanding_agent_requests () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmp_agent.c:3169
#19 0x00403f78 in receive () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1379
#20 0x00402f6c in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/agent/snmpd.c:1125`
