### ISSUE TITLE
snmpd: get_target_sessions returns already deleted session after killing snmptrap 

### ISSUE THREAD

**Issue by emilbart** [net-snmp/net-snmp#187]
I found one problem when running snmpd (from net-snmp version is 5.8 and on ubuntu) under valgrind:

```
==22001== Invalid read of size 8
==22001==    at 0x5112202: get_target_sessions (target.c:302)
==22001==    by 0x5140A77: send_notifications (snmpNotifyTable_data.c:222)
==22001==    by 0x557E7F5: snmp_call_callbacks (callback.c:363)
==22001==    by 0x4E760B5: netsnmp_send_traps (agent_trap.c:1033)
==22001==    by 0x4E76128: send_enterprise_trap_vars (agent_trap.c:1047)
==22001==    by 0x4E77223: send_trap_vars (agent_trap.c:1311)
==22001==    by 0x4E99BB4: agentx_notify (master_admin.c:456)
==22001==    by 0x4E9A116: handle_master_agentx_packet (master_admin.c:554)
==22001==    by 0x5551C5B: _sess_process_packet_handle_pdu (snmp_api.c:5804)
==22001==    by 0x5551DE2: _sess_process_packet (snmp_api.c:5860)
==22001==    by 0x55533B3: _sess_read (snmp_api.c:6286)
==22001==    by 0x555388D: snmp_sess_read2 (snmp_api.c:6394)
==22001==  Address 0x7a8b9b0 is 448 bytes inside a block of size 488 free'd
==22001==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22001==    by 0x5543450: snmp_free_session (snmp_api.c:1931)
==22001==    by 0x5543723: snmp_sess_close (snmp_api.c:2016)
==22001==    by 0x5543802: snmp_close (snmp_api.c:2046)
==22001==    by 0x5553CE7: snmp_sess_select_info2_flags (snmp_api.c:6556)
==22001==    by 0x5553ACF: snmp_sess_select_info2 (snmp_api.c:6486)
==22001==    by 0x555393C: snmp_select_info2 (snmp_api.c:6442)
==22001==    by 0x10C7CD: receive (snmpd.c:1262)
==22001==    by 0x10C372: main (snmpd.c:1125)
==22001==  Block was alloc'd at
==22001==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22001==    by 0x554124B: _sess_copy (snmp_api.c:1099)
==22001==    by 0x55419AD: snmp_sess_copy (snmp_api.c:1312)
==22001==    by 0x5542D93: snmp_sess_add_ex (snmp_api.c:1821)
==22001==    by 0x5542A94: snmp_add (snmp_api.c:1717)
==22001==    by 0x4E74CCD: netsnmp_create_v1v2_notification_session (agent_trap.c:429)
==22001==    by 0x4E776DD: _parse_config_sink (agent_trap.c:1511)
==22001==    by 0x4E7776C: snmpd_parse_config_trap2sink (agent_trap.c:1532)
==22001==    by 0x556AE82: run_config_handler (read_config.c:558)
==22001==    by 0x556C524: read_config (read_config.c:977)
==22001==    by 0x556ABAC: read_config_with_type_when (read_config.c:498)
==22001==    by 0x556C914: read_configs_optional (read_config.c:1035)
==22001== 
==22001== Invalid write of size 8
==22001==    at 0x5112241: get_target_sessions (target.c:303)
==22001==    by 0x5140A77: send_notifications (snmpNotifyTable_data.c:222)
==22001==    by 0x557E7F5: snmp_call_callbacks (callback.c:363)
==22001==    by 0x4E760B5: netsnmp_send_traps (agent_trap.c:1033)
==22001==    by 0x4E76128: send_enterprise_trap_vars (agent_trap.c:1047)
==22001==    by 0x4E77223: send_trap_vars (agent_trap.c:1311)
==22001==    by 0x4E99BB4: agentx_notify (master_admin.c:456)
==22001==    by 0x4E9A116: handle_master_agentx_packet (master_admin.c:554)
==22001==    by 0x5551C5B: _sess_process_packet_handle_pdu (snmp_api.c:5804)
==22001==    by 0x5551DE2: _sess_process_packet (snmp_api.c:5860)
==22001==    by 0x55533B3: _sess_read (snmp_api.c:6286)
==22001==    by 0x555388D: snmp_sess_read2 (snmp_api.c:6394)
==22001==  Address 0x7a8b9b0 is 448 bytes inside a block of size 488 free'd
==22001==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22001==    by 0x5543450: snmp_free_session (snmp_api.c:1931)
==22001==    by 0x5543723: snmp_sess_close (snmp_api.c:2016)
==22001==    by 0x5543802: snmp_close (snmp_api.c:2046)
==22001==    by 0x5553CE7: snmp_sess_select_info2_flags (snmp_api.c:6556)
==22001==    by 0x5553ACF: snmp_sess_select_info2 (snmp_api.c:6486)
==22001==    by 0x555393C: snmp_select_info2 (snmp_api.c:6442)
==22001==    by 0x10C7CD: receive (snmpd.c:1262)
==22001==    by 0x10C372: main (snmpd.c:1125)
==22001==  Block was alloc'd at
==22001==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22001==    by 0x554124B: _sess_copy (snmp_api.c:1099)
==22001==    by 0x55419AD: snmp_sess_copy (snmp_api.c:1312)
==22001==    by 0x5542D93: snmp_sess_add_ex (snmp_api.c:1821)
==22001==    by 0x5542A94: snmp_add (snmp_api.c:1717)
==22001==    by 0x4E74CCD: netsnmp_create_v1v2_notification_session (agent_trap.c:429)
==22001==    by 0x4E776DD: _parse_config_sink (agent_trap.c:1511)
==22001==    by 0x4E7776C: snmpd_parse_config_trap2sink (agent_trap.c:1532)
==22001==    by 0x556AE82: run_config_handler (read_config.c:558)
==22001==    by 0x556C524: read_config (read_config.c:977)
==22001==    by 0x556ABAC: read_config_with_type_when (read_config.c:498)
==22001==    by 0x556C914: read_configs_optional (read_config.c:1035)
==22001== 
==22001== Invalid write of size 8
==22001==    at 0x511225D: get_target_sessions (target.c:308)
==22001==    by 0x5140A77: send_notifications (snmpNotifyTable_data.c:222)
==22001==    by 0x557E7F5: snmp_call_callbacks (callback.c:363)
==22001==    by 0x4E760B5: netsnmp_send_traps (agent_trap.c:1033)
==22001==    by 0x4E76128: send_enterprise_trap_vars (agent_trap.c:1047)
==22001==    by 0x4E77223: send_trap_vars (agent_trap.c:1311)
==22001==    by 0x4E99BB4: agentx_notify (master_admin.c:456)
==22001==    by 0x4E9A116: handle_master_agentx_packet (master_admin.c:554)
==22001==    by 0x5551C5B: _sess_process_packet_handle_pdu (snmp_api.c:5804)
==22001==    by 0x5551DE2: _sess_process_packet (snmp_api.c:5860)
==22001==    by 0x55533B3: _sess_read (snmp_api.c:6286)
==22001==    by 0x555388D: snmp_sess_read2 (snmp_api.c:6394)
==22001==  Address 0x7a8b818 is 40 bytes inside a block of size 488 free'd
==22001==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22001==    by 0x5543450: snmp_free_session (snmp_api.c:1931)
==22001==    by 0x5543723: snmp_sess_close (snmp_api.c:2016)
==22001==    by 0x5543802: snmp_close (snmp_api.c:2046)
==22001==    by 0x5553CE7: snmp_sess_select_info2_flags (snmp_api.c:6556)
==22001==    by 0x5553ACF: snmp_sess_select_info2 (snmp_api.c:6486)
==22001==    by 0x555393C: snmp_select_info2 (snmp_api.c:6442)
==22001==    by 0x10C7CD: receive (snmpd.c:1262)
==22001==    by 0x10C372: main (snmpd.c:1125)
==22001==  Block was alloc'd at
==22001==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22001==    by 0x554124B: _sess_copy (snmp_api.c:1099)
==22001==    by 0x55419AD: snmp_sess_copy (snmp_api.c:1312)
==22001==    by 0x5542D93: snmp_sess_add_ex (snmp_api.c:1821)
==22001==    by 0x5542A94: snmp_add (snmp_api.c:1717)
==22001==    by 0x4E74CCD: netsnmp_create_v1v2_notification_session (agent_trap.c:429)
==22001==    by 0x4E776DD: _parse_config_sink (agent_trap.c:1511)
==22001==    by 0x4E7776C: snmpd_parse_config_trap2sink (agent_trap.c:1532)
==22001==    by 0x556AE82: run_config_handler (read_config.c:558)
==22001==    by 0x556C524: read_config (read_config.c:977)
==22001==    by 0x556ABAC: read_config_with_type_when (read_config.c:498)
==22001==    by 0x556C914: read_configs_optional (read_config.c:1035)

```

Steps to reproduce:

1. Run snmptrapd:
snmptrapd -f -Lo -C -c ../../bs-snmp-linux/snmptrapd.conf tcp:1562

2. Run snmpd
snmpd_valgrind  -f -Lo -C -c ../snmpd3.conf

3. Run agent which sends traps.
4. Send first trap from agent.
5. After receiving the trap by snmptrapd kill snmptrapd.
pkill snmptrapd

6. Send trap from agent.
7. You should get the problem reported by valgrind.

The content of files:
1. snmpd3.conf 
```
$ cat ../snmpd3.conf 
#agentaddress udp:161
agentaddress tcp:1561

rwcommunity public 127.0.0.1 
#wilk
rwcommunity public 

#com2sec readwrite  default         public


sysLocation    POSIX BS2000 17_53
sysContact     Me <me@example.org>
sysServices    76


trap2sink   tcp:127.0.0.1:1562 public
#wilk
#trap2sink   tcp:10.172.192.42:1562  public
#trap2sink   tcp:10.0.3.15:1562 public

master          agentx
agentXSocket    tcp:127.0.0.1:1505
agentXTimeout 5

```
2. snmptrapd.conf
```
$ cat ../snmptrapd.conf
authCommunity log,execute,net public

```
So all communication is by TCP.

I suspect that problem is because the function get_target_sessions returns the pointer to session which was already freed, when connection was closed by snmptrapd, in the following flow:

```
Breakpoint 4, snmp_free_session (s=0x555555865030) at snmp_api.c:1911
(gdb) bt
#0  snmp_free_session (s=0x555555865030) at snmp_api.c:1911
#1  0x00007ffff73d373a in snmp_sess_close (sessp=0x55555585f660) at snmp_api.c:2019
#2  0x00007ffff73d3819 in snmp_close (session=0x555555865030) at snmp_api.c:2049
#3  0x00007ffff73e3cfe in snmp_sess_select_info2_flags (sessp=0x0, numfds=0x7fffffffcf58, fdset=0x7fffffffcf80, timeout=0x7fffffffcf70, block=0x7fffffffcf60, flags=0) at snmp_api.c:6559
#4  0x00007ffff73e3ae6 in snmp_sess_select_info2 (sessp=0x0, numfds=0x7fffffffcf58, fdset=0x7fffffffcf80, timeout=0x7fffffffcf70, block=0x7fffffffcf60) at snmp_api.c:6489
#5  0x00007ffff73e3953 in snmp_select_info2 (numfds=0x7fffffffcf58, fdset=0x7fffffffcf80, timeout=0x7fffffffcf70, block=0x7fffffffcf60) at snmp_api.c:6445
#6  0x00005555555587ce in receive () at snmpd.c:1262
#7  0x0000555555558373 in main (argc=6, argv=0x7fffffffd2f8) at snmpd.c:1125

```

but that session was not removed from list aAddrTable. The session was added to that list during starting of program when the connection was established, see the flow:

```
Breakpoint 2, snmpTargetAddrTable_addToList (newEntry=0x5555558652e0, listPtr=0x7ffff7b0bfc0 <aAddrTable>) at target/snmpTargetAddrEntry_data.c:124
124	    if ((prev_struct = curr_struct = *listPtr) == NULL) {
(gdb) bt
#0  snmpTargetAddrTable_addToList (newEntry=0x5555558652e0, listPtr=0x7ffff7b0bfc0 <aAddrTable>) at target/snmpTargetAddrEntry_data.c:124
#1  0x00007ffff77bd1c9 in snmpTargetAddrTable_add (newEntry=0x5555558652e0) at target/snmpTargetAddrEntry_data.c:172
#2  0x00007ffff77b5cf4 in notifyTable_register_notifications (major=1, minor=8, serverarg=0x7fffffffacd0, clientarg=0x0) at notification/snmpNotifyTable_data.c:366
#3  0x00007ffff740e80d in snmp_call_callbacks (major=1, minor=8, caller_arg=0x7fffffffacd0) at callback.c:363
#4  0x00007ffff7b9b556 in netsnmp_add_notification_session (ss=0x555555865030, pdutype=167, confirm=0, version=1, name=0x0, tag=0x0, profile=0x0) at agent_trap.c:265
#5  0x00007ffff7b9bde5 in netsnmp_create_v1v2_notification_session (sink=0x55555586347c "tcp:127.0.0.1:1562", sinkport=0x0, com=0x55555586348f "public", src=0x0, version=1, pdutype=167, name=0x0, tag=0x0, 
    profile=0x0) at agent_trap.c:438
#6  0x00007ffff7b9e77d in _parse_config_sink (token=0x7fffffffbbc0 "trap2sink", cptr=0x55555586347c "tcp:127.0.0.1:1562", version=1, type=167) at agent_trap.c:1511
#7  0x00007ffff7b9e80c in snmpd_parse_config_trap2sink (word=0x7fffffffbbc0 "trap2sink", cptr=0x55555586347c "tcp:127.0.0.1:1562") at agent_trap.c:1532
#8  0x00007ffff73fae99 in run_config_handler (lptr=0x55555575d330, token=0x7fffffffbbc0 "trap2sink", cptr=0x55555586347c "tcp:127.0.0.1:1562", when=0) at read_config.c:558
#9  0x00007ffff73fc53b in read_config (filename=0x55555585f690 "../snmpd3.conf", line_handler=0x55555575d200, when=0) at read_config.c:977
#10 0x00007ffff73fabc3 in read_config_with_type_when (filename=0x55555585f690 "../snmpd3.conf", type=0x55555575c420 "snmpd", when=0) at read_config.c:498
#11 0x00007ffff73fc92b in read_configs_optional (optional_config=0x55555575c2f0 "../snmpd3.conf", when=0) at read_config.c:1035
#12 0x00007ffff73fcaaa in read_configs () at read_config.c:1066
#13 0x00007ffff73d0d8b in init_snmp (type=0x555555558de0 "snmpd") at snmp_api.c:914
#14 0x0000555555557d19 in main (argc=6, argv=0x7fffffffd2f8) at snmpd.c:947
```

so when we want to send next  traps to not running snmptrapd the function get_target_sessions return pointer to freed memory.
I have not observed the crash.
Also the strange thing is that the connection (snmpd - snmptrapd) is not restored when we re-run snmptrapd.

**Comment by emilbart** [comment]
I'm trying to make a fix for the problem but I need some clue what should be the proper solution.
It seems that somehow the callback SNMPD_CALLBACK_UNREGISTER_NOTIFICATIONS should be called when the remote connection is closed in agent_trap.c. So I was thinking to add callback to sink2trap session and call SNMPD_CALLBACK_UNREGISTER_NOTIFICATIONS there, see:

```
netsnmp_session *
netsnmp_create_v1v2_notification_session(const char *sink, const char* sinkport,
                                         const char *com, const char *src,
                                         int version, int pdutype,
                                         const char *name, const char *tag,
                                         const char* profile)
{
...
    snmp_sess_init(&session);
+   session.callback = handle_disconnect_packet;

...
}

static int handle_disconnect_packet(int op, netsnmp_session *session, int reqid,
                                    netsnmp_pdu *pdu, void *magic)
{
    /*
     * We only support disconnect package here.
     */
    if (NETSNMP_CALLBACK_OP_DISCONNECT == op) {
        netsnmp_unregister_notification(session->paramName, strlen(session->paramName));
    }

    return 1;
}

```
Unfortunately this also gives some problems because when we call SNMPD_CALLBACK_UNREGISTER_NOTIFICATIONS  it also frees the session which we are handling. So we frees the session in the middle of closing session, so we have invalid pointer inside function snmp_read2.
Any hints?

**Comment by bvanassche** [comment]
Net-SNMP v5.8 is no longer supported. Since the code shown in this bug report has been modified, please retest with v5.9 or the master branch.

**Comment by emilbart** [comment]
Retested with v5.9 and master branch. Got the same result. Valgrind output for master branch:

```
==3979== Invalid read of size 8
==3979==    at 0x50FD489: get_target_sessions (target.c:301)
==3979==    by 0x512015C: send_notifications (snmpNotifyTable_data.c:222)
==3979==    by 0x5536E25: snmp_call_callbacks (callback.c:360)
==3979==    by 0x4E6F9E5: netsnmp_send_traps (agent_trap.c:971)
==3979==    by 0x4E6FD3D: send_enterprise_trap_vars (agent_trap.c:989)
==3979==    by 0x4E8CC9C: agentx_notify (master_admin.c:452)
==3979==    by 0x4E8D182: handle_master_agentx_packet (master_admin.c:549)
==3979==    by 0x5514E66: _sess_process_packet_handle_pdu (snmp_api.c:5809)
==3979==    by 0x5514E66: _sess_process_packet (snmp_api.c:5858)
==3979==    by 0x5515D46: _sess_read (snmp_api.c:6280)
==3979==    by 0x55168D8: snmp_sess_read2 (snmp_api.c:6387)
==3979==    by 0x551692A: snmp_read2 (snmp_api.c:5907)
==3979==    by 0x10C7C3: receive (snmpd.c:1307)
==3979==  Address 0x73b6d70 is 448 bytes inside a block of size 488 free'd
==3979==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x550DAC7: snmp_sess_close (snmp_api.c:2000)
==3979==    by 0x550F8DE: snmp_sess_select_info2_flags (snmp_api.c:6548)
==3979==    by 0x10C339: receive (snmpd.c:1228)
==3979==    by 0x10B323: main (snmpd.c:1085)
==3979==  Block was alloc'd at
==3979==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x552C618: netsnmp_memdup (tools.c:285)
==3979==    by 0x550DBE8: _sess_copy (snmp_api.c:1094)
==3979==    by 0x550DBE8: snmp_sess_copy (snmp_api.c:1297)
==3979==    by 0x550DBE8: snmp_sess_add_ex (snmp_api.c:1805)
==3979==    by 0x550E577: snmp_add (snmp_api.c:1707)
==3979==    by 0x4E6E907: netsnmp_create_v1v2_notification_session (agent_trap.c:372)
==3979==    by 0x4E6ECBC: _parse_config_sink.isra.4 (agent_trap.c:1464)
==3979==    by 0x5528073: run_config_handler (read_config.c:541)
==3979==    by 0x5528C2E: read_config (read_config.c:960)
==3979==    by 0x55296F5: read_configs_optional (read_config.c:1018)
==3979==    by 0x552A1D1: read_configs (read_config.c:1049)
==3979==    by 0x10AEC0: main (snmpd.c:911)
==3979== 
==3979== Invalid write of size 8
==3979==    at 0x50FD4AC: get_target_sessions (target.c:302)
==3979==    by 0x512015C: send_notifications (snmpNotifyTable_data.c:222)
==3979==    by 0x5536E25: snmp_call_callbacks (callback.c:360)
==3979==    by 0x4E6F9E5: netsnmp_send_traps (agent_trap.c:971)
==3979==    by 0x4E6FD3D: send_enterprise_trap_vars (agent_trap.c:989)
==3979==    by 0x4E8CC9C: agentx_notify (master_admin.c:452)
==3979==    by 0x4E8D182: handle_master_agentx_packet (master_admin.c:549)
==3979==    by 0x5514E66: _sess_process_packet_handle_pdu (snmp_api.c:5809)
==3979==    by 0x5514E66: _sess_process_packet (snmp_api.c:5858)
==3979==    by 0x5515D46: _sess_read (snmp_api.c:6280)
==3979==    by 0x55168D8: snmp_sess_read2 (snmp_api.c:6387)
==3979==    by 0x551692A: snmp_read2 (snmp_api.c:5907)
==3979==    by 0x10C7C3: receive (snmpd.c:1307)
==3979==  Address 0x73b6d70 is 448 bytes inside a block of size 488 free'd
==3979==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x550DAC7: snmp_sess_close (snmp_api.c:2000)
==3979==    by 0x550F8DE: snmp_sess_select_info2_flags (snmp_api.c:6548)
==3979==    by 0x10C339: receive (snmpd.c:1228)
==3979==    by 0x10B323: main (snmpd.c:1085)
==3979==  Block was alloc'd at
==3979==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x552C618: netsnmp_memdup (tools.c:285)
==3979==    by 0x550DBE8: _sess_copy (snmp_api.c:1094)
==3979==    by 0x550DBE8: snmp_sess_copy (snmp_api.c:1297)
==3979==    by 0x550DBE8: snmp_sess_add_ex (snmp_api.c:1805)
==3979==    by 0x550E577: snmp_add (snmp_api.c:1707)
==3979==    by 0x4E6E907: netsnmp_create_v1v2_notification_session (agent_trap.c:372)
==3979==    by 0x4E6ECBC: _parse_config_sink.isra.4 (agent_trap.c:1464)
==3979==    by 0x5528073: run_config_handler (read_config.c:541)
==3979==    by 0x5528C2E: read_config (read_config.c:960)
==3979==    by 0x55296F5: read_configs_optional (read_config.c:1018)
==3979==    by 0x552A1D1: read_configs (read_config.c:1049)
==3979==    by 0x10AEC0: main (snmpd.c:911)
==3979== 
==3979== Invalid write of size 8
==3979==    at 0x50FD1A2: get_target_sessions (target.c:307)
==3979==    by 0x512015C: send_notifications (snmpNotifyTable_data.c:222)
==3979==    by 0x5536E25: snmp_call_callbacks (callback.c:360)
==3979==    by 0x4E6F9E5: netsnmp_send_traps (agent_trap.c:971)
==3979==    by 0x4E6FD3D: send_enterprise_trap_vars (agent_trap.c:989)
==3979==    by 0x4E8CC9C: agentx_notify (master_admin.c:452)
==3979==    by 0x4E8D182: handle_master_agentx_packet (master_admin.c:549)
==3979==    by 0x5514E66: _sess_process_packet_handle_pdu (snmp_api.c:5809)
==3979==    by 0x5514E66: _sess_process_packet (snmp_api.c:5858)
==3979==    by 0x5515D46: _sess_read (snmp_api.c:6280)
==3979==    by 0x55168D8: snmp_sess_read2 (snmp_api.c:6387)
==3979==    by 0x551692A: snmp_read2 (snmp_api.c:5907)
==3979==    by 0x10C7C3: receive (snmpd.c:1307)
==3979==  Address 0x73b6bd8 is 40 bytes inside a block of size 488 free'd
==3979==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x550DAC7: snmp_sess_close (snmp_api.c:2000)
==3979==    by 0x550F8DE: snmp_sess_select_info2_flags (snmp_api.c:6548)
==3979==    by 0x10C339: receive (snmpd.c:1228)
==3979==    by 0x10B323: main (snmpd.c:1085)
==3979==  Block was alloc'd at
==3979==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x552C618: netsnmp_memdup (tools.c:285)
==3979==    by 0x550DBE8: _sess_copy (snmp_api.c:1094)
==3979==    by 0x550DBE8: snmp_sess_copy (snmp_api.c:1297)
==3979==    by 0x550DBE8: snmp_sess_add_ex (snmp_api.c:1805)
==3979==    by 0x550E577: snmp_add (snmp_api.c:1707)
==3979==    by 0x4E6E907: netsnmp_create_v1v2_notification_session (agent_trap.c:372)
==3979==    by 0x4E6ECBC: _parse_config_sink.isra.4 (agent_trap.c:1464)
==3979==    by 0x5528073: run_config_handler (read_config.c:541)
==3979==    by 0x5528C2E: read_config (read_config.c:960)
==3979==    by 0x55296F5: read_configs_optional (read_config.c:1018)
==3979==    by 0x552A1D1: read_configs (read_config.c:1049)
==3979==    by 0x10AEC0: main (snmpd.c:911)
==3979== 
==3979== Invalid read of size 8
==3979==    at 0x51201A7: send_notifications (snmpNotifyTable_data.c:230)
==3979==    by 0x5536E25: snmp_call_callbacks (callback.c:360)
==3979==    by 0x4E6F9E5: netsnmp_send_traps (agent_trap.c:971)
==3979==    by 0x4E6FD3D: send_enterprise_trap_vars (agent_trap.c:989)
==3979==    by 0x4E8CC9C: agentx_notify (master_admin.c:452)
==3979==    by 0x4E8D182: handle_master_agentx_packet (master_admin.c:549)
==3979==    by 0x5514E66: _sess_process_packet_handle_pdu (snmp_api.c:5809)
==3979==    by 0x5514E66: _sess_process_packet (snmp_api.c:5858)
==3979==    by 0x5515D46: _sess_read (snmp_api.c:6280)
==3979==    by 0x55168D8: snmp_sess_read2 (snmp_api.c:6387)
==3979==    by 0x551692A: snmp_read2 (snmp_api.c:5907)
==3979==    by 0x10C7C3: receive (snmpd.c:1307)
==3979==    by 0x10B323: main (snmpd.c:1085)
==3979==  Address 0x73b6bb0 is 0 bytes inside a block of size 488 free'd
==3979==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x550DAC7: snmp_sess_close (snmp_api.c:2000)
==3979==    by 0x550F8DE: snmp_sess_select_info2_flags (snmp_api.c:6548)
==3979==    by 0x10C339: receive (snmpd.c:1228)
==3979==    by 0x10B323: main (snmpd.c:1085)
==3979==  Block was alloc'd at
==3979==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3979==    by 0x552C618: netsnmp_memdup (tools.c:285)
==3979==    by 0x550DBE8: _sess_copy (snmp_api.c:1094)
==3979==    by 0x550DBE8: snmp_sess_copy (snmp_api.c:1297)
==3979==    by 0x550DBE8: snmp_sess_add_ex (snmp_api.c:1805)
==3979==    by 0x550E577: snmp_add (snmp_api.c:1707)
==3979==    by 0x4E6E907: netsnmp_create_v1v2_notification_session (agent_trap.c:372)
==3979==    by 0x4E6ECBC: _parse_config_sink.isra.4 (agent_trap.c:1464)
==3979==    by 0x5528073: run_config_handler (read_config.c:541)
==3979==    by 0x5528C2E: read_config (read_config.c:960)
==3979==    by 0x55296F5: read_configs_optional (read_config.c:1018)
==3979==    by 0x552A1D1: read_configs (read_config.c:1049)
==3979==    by 0x10AEC0: main (snmpd.c:911)
```

**Comment by emilbart** [comment]
The configure parameters:
./configure --with-enterprise-oid=231 --with-enterprise-sysoid=1.3.6.1.4.1.231.2.17.2.43 --with-sys-contact=snmpinfo@ala.com --with-sys-location="test" --with-default-snmp-version=3 --with-logfile=/var/log/snmpd.log --with-persistent-directory=/var/net-snmp --with-mibdirs=/usr/share/snmp/mibs --sysconfdir=/etc --enable-ipv6 --disable-embedded-perl --disable-perl-cc-checks --with-openssl=/usr/local/openssl/openssl-1.1.1g/ --with-out-mib-modules="ucd_snmp" --disable-scripts --with-mib-modules="agent/extend ucd-snmp/versioninfo ucd-snmp/pass ucd-snmp/pass_persist ucd-snmp/errormib ucd-snmp/proxy ucd-snmp/pass_common util_funcs/restart  mibII/data_access/at_unix" --disable-manuals
