### ISSUE TITLE
Segfault on usm_free_usmStateReference when compiled with -O2

### ISSUE THREAD

**Issue by pupper68k** [net-snmp/net-snmp#22]
Issue was reproduced on a 64 bit Big Endian PowerPC machine.
We found it very challenging to reproduce this issue, except on a machine in production that reproduced it reliably.

The segfaults went away when we compiled with -Og, but returned when we went back to compiling with -O2. We added a debug print in usm_free_usmStateReference on line 300 of snmplib/snmpusm.c (before the if (old_ref) check)
```
snmp_log(LOG_WARNING, "[+] SNMP USM FREE: %i", (uint64_t) old_ref);
```
Adding the above line cause the issue to stop reproducing. This leads me to believe that the compiler optimizations were somehow bypassing the if(old_ref) check for null references at level -O2.

Below is a stack trace I gathered from GDB
```
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc64-nptl-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/snmpd...done.
[New LWP 17608]

warning: .dynamic section for "/lib64/libnetsnmpmibs.so.35" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libnetsnmp.so.35" is not at the expected address (wrong library or version mismatch?)

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/snmpd -f -p /var/run/net-snmp/snmpd.pid -c /etc/snmpd.conf -Le -Dwatc'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00003fff79e4a030 in .raise () from /lib64/libc.so.6
(gdb) bt full
#0  0x00003fff79e4a030 in .raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00003fff79e4bc9c in .abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00003fff79e8f8a0 in ?? () from /lib64/libc.so.6
No symbol table info available.
#3  0x00003fff79e97d84 in ?? () from /lib64/libc.so.6
No symbol table info available.
#4  0x00003fff79e98ddc in ?? () from /lib64/libc.so.6
No symbol table info available.
#5  0x00003fff7a4a3068 in usm_free_usmStateReference (old=0x0) at snmpusm.c:302
        old_ref = 0x0
#6  0x00003fff7a4a5dc8 in usm_generate_out_msg (msgProcModel=<optimized out>, globalData=0x1014d060, globalDataLen=7, maxMsgSize=<optimized out>, secModel=<optimized out>, 
    secEngineID=<optimized out>, secEngineIDLen=<optimized out>, secName=<optimized out>, secNameLen=10, secLevel=3, scopedPdu=0x3ffff9e92a30 "0\202\005\271\004\022\200", scopedPduLen=1469, 
    secStateRef=0x10128510, secParams=0x1014d07a, secParamsLen=0x3ffff9e93098, wholeMsg=0x3ffff9e93088, 
    wholeMsgLen=0x3ffff9e932e0) at snmpusm.c:1168
        encrypted_length = 2604281822446170256
        salt_length = 70368642017376
        salt = ...
        priv_type = <optimized out>
        otstlen = 36
        seq_len = 32
        msgAuthParmLen = 0
        msgPrivParmLen = 0
        msgSecParmLen = 38
        authParamsOffset = 62
        privParamsOffset = 64
        datalen = 1469
        dataOffset = 64
        theTotalLength = 1533
        ptr = 0x1014d060 
        ptr_len = <optimized out>
        remaining = 70368642017376
        offSet = <optimized out>
        boots_uint = 1
        time_uint = 3
        boots_long = 1
        time_long = 3
        theName = 0x3fff7a856000 
        theNameLength = 80
        theEngineID = 0x3ffff9e922e0 
        theEngineIDLength = 7
        theAuthKey = 0x10128510 
        theAuthKeyLength = 0
        theAuthProtocol = 0x0
        theAuthProtocolLength = 0
        thePrivKey = 0x0
        thePrivKeyLength = 0
        thePrivProtocol = 0x0
        thePrivProtocolLength = 0
        theSecLevel = 80
#7  0x00003fff7a4a60a0 in usm_secmod_generate_out_msg (parms=<optimized out>) at snmpusm.c:872
No locals.
#8  0x00003fff7a46e218 in snmpv3_packet_build (session=0x10128920, pdu=0x1013d960, packet=0x1014d060, out_length=0x3ffff9e932e0, pdu_data=<optimized out>, pdu_data_len=<optimized out>)
    at snmp_api.c:2795
        parms = {msgProcModel = 0, globalData = 0x1014d060, globalDataLen = 26, maxMsgSize = 1472, secModel = 3, secEngineID = 0x1013daa0, secEngineIDLen = 18, 
          secName = 0x1013dae0, secNameLen = 10, secLevel = 3, scopedPdu = 0x3ffff9e92a30, scopedPduLen = 1469, secStateRef = 0x10128510, 
          secParams = 0x1014d07a, secParamsLen = 0x3ffff9e93098, wholeMsg = 0x3ffff9e93088, wholeMsgLen = 0x3ffff9e932e0, 
          wholeMsgOffset = 0x3fff7a844870, pdu = 0x1013d960, session = 0x10128920}
        global_data = 0x1014d060 
        spdu_hdr_e = 0x3ffff9e92a34 
        global_data_len = 26
        sec_params_len = 1438
        spdu_buf = ...
        spdu_buf_len = 1468
        spdu_len = <optimized out>
        cp = <optimized out>
        sptr = <optimized out>
#9  0x00003fff7a46e96c in snmpv3_build (pdu=0x1013d960, session=0x10128920, offset=0x3ffff9e93240, pkt_len=0x3ffff9e932e0, pkt=0x3ffff9e932f8) at snmp_api.c:2272
        ret = <optimized out>
#10 _snmp_build (pdu=0x1013d960, session=0x10128920, offset=0x3ffff9e93240, pkt_len=0x3ffff9e932e0, pkt=0x3ffff9e932f8) at snmp_api.c:2853
        h0e = 0x0
        start_offset = 0
        length = 70366500400992
        version = 0
        rc = 0
        cp = <optimized out>
#11 snmp_build (pkt=0x3ffff9e932f8, pkt_len=0x3ffff9e932e0, offset=0x3ffff9e93240, pss=0x10128920, pdu=0x1013d960) at snmp_api.c:3192
No locals.
#12 0x00003fff7a46ecd4 in netsnmp_build_packet (isp=<optimized out>, sp=<optimized out>, pdu=<optimized out>, pktbuf_p=0x3ffff9e932f8, pktbuf_len_p=0x3ffff9e932e8, pkt_p=<optimized out>, 
    len_p=0x3ffff9e932e0) at snmp_api.c:4962
        offset = 0
        result = <optimized out>
#13 0x00003fff7a46ef28 in _build_initial_pdu_packet (slp=<optimized out>, pdu=0x1013d960, bulk=<optimized out>) at snmp_api.c:5122
        session = 0x10128920
        isp = 0x10128890
        transport = <optimized out>
        pktbuf = <optimized out>
        packet = 0x1014d060 
        pktbuf_len = 1472
        length = 1472
        orig_length = <optimized out>
        result = <optimized out>
        orig_count = <optimized out>
        curr_count = <optimized out>
#14 0x00003fff7a7f9d8c in netsnmp_wrap_up_request (asp=0x1013d8e0, status=0) at snmp_agent.c:1987
        var_ptr = <optimized out>
        i = 1
#15 0x00003fff7a7fc5ac in netsnmp_handle_request (asp=0x1013d8e0, status=<optimized out>) at snmp_agent.c:3644
No locals.
#16 0x00003fff7a7fc86c in handle_snmp_packet (op=<optimized out>, session=<optimized out>, reqid=<optimized out>, pdu=<optimized out>, magic=<optimized out>) at snmp_agent.c:2298
No locals.
Backtrace stopped: frame did not save the PC
```

**Comment by bvanassche** [comment]
If this happened with version v5.8, please retest with the latest version of the v5.8 branch. See also https://github.com/net-snmp/net-snmp/tree/V5-8-patches.
