### ISSUE TITLE
Several core dumps of snmpd (net-snmp 5.8)

### ISSUE THREAD

**Issue by krishnacx** [net-snmp/net-snmp#292]
Multiple core files are generated when monitoring a management server

SNMPd.conf
*********************************
sysContact AAAA@XXX.com
sysLocation FR-PAR,PAR7-1R126,D02,38-39
sysName FR-PAR-EXT-LBA-01
# snmpd Configuration File
# The following are example for snmpd.conf.
#
#SNMP Trap Destination example
#trap2sink 1.2.3.4:162 public
sysobjectid 1.3.6.1.4.1.5951.6
[snmp] logTimestamp 1
exactEngineID 0x80001f888082c995074288e05500000000
view TIVOLI included 1.3.6.1
rouser itnmusr authPriv -V TIVOLI
rouser visionuser authPriv -V TIVOLI
rouser eudediscosnmp authPriv -V TIVOLI
trapsess -v 3 -u itnmusr -l authPriv 10.72.80.52:162
trapsess -v 3 -u itnmusr -l authPriv 10.72.80.53:162
trapsess -v 3 -u visionuser -l authPriv 10.72.226.227:162
rocommunity public 10.72.80.52
rocommunity public 10.72.80.53
rocommunity J3n7wc7p4Zau 10.72.226.227

*********************************

 **_**_**1 upload upload 5.3M Mar 30 10:30 snmpd-89278
 1 upload upload 7.3M Mar 30 11:51 snmpd-92711
 1 upload upload 5.3M Mar 30 13:30 snmpd-97291
 1 upload upload 7.3M Mar 30 14:41 snmpd-340
 1 upload upload 5.3M Mar 30 16:40 snmpd-5755**_**_**

They all ended up with below backtrace:

#0 0x0000000800d99e64 in md5_block_asm_data_order () from /lib/libcrypto.so.6
#1 0x0000000000000003 in ?? ()
#2 0x0000000001c47c40 in ?? ()
#3 0x00000000000711f1 in ?? ()
#4 0x0000000801d3e080 in ?? ()
#5 0x0000000800d99e06 in MD5_Update () from /lib/libcrypto.so.6
#6 0x00000008009564d6 in sc_hash_type () from /lib/libnetsnmp.so.35
#7 0x000000080095639d in sc_hash () from /lib/libnetsnmp.so.35
#8 0x0000000800953817 in hash_engineID () from /lib/libnetsnmp.so.35
#9 0x0000000800953720 in search_enginetime_list () from /lib/libnetsnmp.so.35
#10 0x0000000800952f06 in get_enginetime () from /lib/libnetsnmp.so.35
#11 0x00000008009748dc in usm_rgenerate_out_msg () from /lib/libnetsnmp.so.35
#12 0x000000080097437a in usm_secmod_rgenerate_out_msg () from /lib/libnetsnmp.so.35
#13 0x0000000800921cb7 in snmpv3_packet_realloc_rbuild () from /lib/libnetsnmp.so.35
#14 0x000000080091fb7d in snmp_close_sessions () from /lib/libnetsnmp.so.35
#15 0x00000008009225f5 in snmpv3_packet_build () from /lib/libnetsnmp.so.35
#16 0x0000000800923898 in snmp_build () from /lib/libnetsnmp.so.35
#17 0x000000080092ab53 in netsnmp_build_packet () from /lib/libnetsnmp.so.35
#18 0x000000080092b255 in _build_initial_pdu_packet () from /lib/libnetsnmp.so.35
#19 0x0000000800689b14 in netsnmp_wrap_up_request () from /lib/libnetsnmpagent.so.35
#20 0x000000080068e098 in netsnmp_handle_request () from /lib/libnetsnmpagent.so.35
#21 0x000000080068a849 in handle_snmp_packet () from /lib/libnetsnmpagent.so.35
#22 0x000000080092cfbe in snmp_create_sess_pdu () from /lib/libnetsnmp.so.35
#23 0x000000080092d158 in snmp_create_sess_pdu () from /lib/libnetsnmp.so.35
#24 0x000000080092dda4 in _sess_read () from /lib/libnetsnmp.so.35
#25 0x000000080092ebbd in snmp_sess_read2 () from /lib/libnetsnmp.so.35
#26 0x000000080092d318 in snmp_read2 () from /lib/libnetsnmp.so.35
#27 0x0000000000404a5a in receive ()
#28 0x00000000004043b2 in main ()

#0 0x00000008015bafe6 in memmove () from /lib/libc.so.7
#1 0x00000008008f9c0c in snmp_clone_var () from /lib/libnetsnmp.so.35
#2 0x00000008008fa1f2 in snmp_reset_var_buffers () from /lib/libnetsnmp.so.35
#3 0x00000008008fa311 in snmp_reset_var_buffers () from /lib/libnetsnmp.so.35
#4 0x00000008008fa367 in snmp_reset_var_buffers () from /lib/libnetsnmp.so.35
#5 0x00000008008fa3ca in snmp_clone_pdu () from /lib/libnetsnmp.so.35
#6 0x000000080068442e in send_trap_to_sess () from /lib/libnetsnmpagent.so.35
#7 0x00000008006835a4 in netsnmp_send_traps () from /lib/libnetsnmpagent.so.35
#8 0x000000080068365f in send_enterprise_trap_vars () from /lib/libnetsnmpagent.so.35
#9 0x00000008006846b6 in send_trap_vars () from /lib/libnetsnmpagent.so.35
#10 0x000000080068477e in send_easy_trap () from /lib/libnetsnmpagent.so.35
#11 0x0000000000404603 in receive ()
#12 0x00000000004043b2 in main ()

Are thre any known issues in this version. It is constantly found that SNMP managers are querying network interface details, health monitoring stats of server

**Comment by krishnacx** [comment]
@bvanassche Could you assist in this case ? and recommended actions

**Comment by bvanassche** [comment]
Net-SNMP v5.8 is no longer supported. Please retest with version v5.9.1.
