### ISSUE TITLE
snmpd crash  - double free or memory corruption

### ISSUE THREAD

**Issue by vickyorlo** [net-snmp/net-snmp#428]
Snmp version: 5.7.3-6.9.1
Linux version: SLES12 v12.5-1.171, Linux 4.12.14-122.121-default

We got a core dump at an essentially random time. Reading the logs doesn't bring any particular cause to mind, and snmp worked perfectly fine after the crash. We couldn't manage to replicate/reproduce this behavior either, Best we've got is a backtrace from gdb:

```
#0  0x00007f92aa13d0d7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f92aa13e4aa in __GI_abort () at abort.c:78
#2  0x00007f92aa17c334 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f92aa2762d8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f92aa1817a6 in malloc_printerr (action=3, str=0x7f92aa276350 "double free or corruption (!prev)", ptr=<optimized out>, ar_ptr=<optimized out>)
    at malloc.c:5018
#4  0x00007f92aa1825eb in _int_free (av=0x7f92aa4a45c0 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:3872
#5  0x00007f92aaecf800 in agentx_got_response (operation=2, session=0x558a9efcfa80, reqid=4357, pdu=0x558a9efc5590, magic=0x558a9efbec80)
    at mibgroup/agentx/master.c:224
#6  0x00007f92aa7096af in snmp_sess_close (sessp=0x558a9efcf550) at snmp_api.c:1874
#7  0x00007f92aa70b35f in snmp_sess_select_info2_flags (sessp=sessp@entry=0x0, numfds=numfds@entry=0x7ffe5b52de14, fdset=fdset@entry=0x7ffe5b52de30,
    timeout=timeout@entry=0x7ffe5b52de20, block=block@entry=0x7ffe5b52de1c, flags=flags@entry=0) at snmp_api.c:6067
#8  0x00007f92aa70b7b8 in snmp_sess_select_info2 (sessp=sessp@entry=0x0, numfds=numfds@entry=0x7ffe5b52de14, fdset=fdset@entry=0x7ffe5b52de30,
    timeout=timeout@entry=0x7ffe5b52de20, block=block@entry=0x7ffe5b52de1c) at snmp_api.c:5997
#9  0x00007f92aa70b7d3 in snmp_select_info2 (numfds=numfds@entry=0x7ffe5b52de14, fdset=fdset@entry=0x7ffe5b52de30, timeout=timeout@entry=0x7ffe5b52de20,
    block=block@entry=0x7ffe5b52de1c) at snmp_api.c:5953
#10 0x0000558a9d8bf551 in receive () at snmpd.c:1249
#11 main (argc=<optimized out>, argv=<optimized out>) at snmpd.c:1115

```

**Comment by bvanassche** [comment]
Please report issues encountered with SLES RPMs to SUSE.
