### ISSUE TITLE
Error [InvalidAsn1Error]: Expected 0x4: got 0x3

### ISSUE THREAD

**Issue by gamadoleo** [net-snmp/net-snmp#533]
Alguem poderia ajudar, alguma forma de contornar esse error? isso está travando minha aplicação...
```
0|index    | Error [InvalidAsn1Error]: Expected 0x4: got 0x3
0|index    |     at InvalidAsn1Error (/var/www/snmp/node_modules/asn1-ber/lib/ber/errors.js:4:11)
0|index    |     at Reader.readString (/var/www/snmp/node_modules/asn1-ber/lib/ber/reader.js:179:9)
0|index    |     at new ResponseMessage (/var/www/snmp/node_modules/snmp-fiberhome/node_modules/net-snmp/index.js:532:26)
0|index    |     at Session.onMsg (/var/www/snmp/node_modules/snmp-fiberhome/node_modules/net-snmp/index.js:911:17)
0|index    |     at Socket.emit (events.js:400:28)
0|index    |     at UDP.onMessage [as onmessage] (dgram.js:931:8)
```

**Comment by bvanassche** [comment]
Please reopen if it can be shown that the above report is related to the Net-SNMP project.
