### ISSUE TITLE
Use 5.8  has met the coredump of glibc

### ISSUE THREAD

**Issue by SunFuchun** [net-snmp/net-snmp#557]
(gdb) bt
#0 _int_malloc (av=av@entry=0x7fb5b8000020, bytes=bytes@entry=61) at malloc.c:3489
#1 0x00007fb5d1270c74 in __GI___libc_malloc (bytes=bytes@entry=61) at malloc.c:2986
#2 0x00007fb5d15b0942 in snmp_clone_mem (dstPtr=dstPtr@entry=0x7fb5b80196b8, srcPtr=0x7fb5b8013980, len=60) at snmp_client.c:308
#3 0x00007fb5d15b0ace in _clone_pdu_header (pdu=pdu@entry=0x7fb5b8013b30) at snmp_client.c:399
#4 0x00007fb5d15b0f7e in _clone_pdu (drop_err=0, pdu=0x7fb5b8013b30) at snmp_client.c:559
#5 snmp_clone_pdu (pdu=pdu@entry=0x7fb5b8013b30) at snmp_client.c:587
#6 0x00007fb5d1d6dc4e in init_agent_snmp_session (session=0x55ca126bc900, pdu=pdu@entry=0x7fb5b8013b30) at snmp_agent.c:1687
#7 0x00007fb5d1d7245b in handle_snmp_packet (op=<optimized out>, session=<optimized out>, reqid=<optimized out>, pdu=0x7fb5b8013b30, magic=0x0) at snmp_agent.c:2347
#8 0x00007fb5d15d9884 in _sess_process_packet_handle_pdu (isp=0x55ca126a8dd0, isp=0x55ca126a8dd0, transport=0x55ca126b7da0, pdu=0x7fb5b8013b30, sp=0x55ca126bc900, sessp=0x55ca1267fca0) at snmp_api.c:5825
#9 _sess_process_packet (sessp=sessp@entry=0x55ca1267fca0, sp=sp@entry=0x55ca126bc900, isp=isp@entry=0x55ca126a8dd0, transport=transport@entry=0x55ca126b7da0, opaque=<optimized out>, olength=<optimized out>, packetptr=0x7fb5b8032a90 "0.\002\001", length=48) at snmp_api.c:5881
#10 0x00007fb5d15daa3a in _sess_read (sessp=sessp@entry=0x55ca1267fca0, fdset=fdset@entry=0x7fff9d297e90) at snmp_api.c:6142
#11 0x00007fb5d15db259 in snmp_sess_read2 (sessp=sessp@entry=0x55ca1267fca0, fdset=fdset@entry=0x7fff9d297e90) at snmp_api.c:6415
#12 0x00007fb5d15db2ab in snmp_read2 (fdset=0x7fff9d297e90) at snmp_api.c:5930
#13 0x000055ca1205f04c in receive () at snmpd.c:1477

Thanks in advance for your comments and suggestions

**Comment by SunFuchun** [comment]
Another core dump has been gotten

(gdb) bt
#0  _int_malloc (av=av@entry=0x7f588709eb40 <main_arena>, bytes=bytes@entry=256) at malloc.c:3589
#1  0x00007f5886d80c74 in __GI___libc_malloc (bytes=bytes@entry=256) at malloc.c:2986
#2  0x00007f58871004a2 in snmp_realloc (buf=buf@entry=0x7ffe5ec94e28, buf_len=buf_len@entry=0x7ffe5ec94e30) at tools.c:180
#3  0x00007f58870c3854 in _sprint_hexstring_line (buf=0x7ffe5ec94e28, buf_len=0x7ffe5ec94e30, out_len=0x7ffe5ec94e38, allow_realloc=1, cp=0x5574809d5cf0 "@", line_len=4) at mib.c:318
#4  0x00007f58870c3b89 in sprint_realloc_hexstring (buf=buf@entry=0x7ffe5ec94e28, buf_len=buf_len@entry=0x7ffe5ec94e30, out_len=out_len@entry=0x7ffe5ec94e38, allow_realloc=allow_realloc@entry=1, cp=cp@entry=0x5574809d5cf0 "@", len=len@entry=4) at mib.c:375
#5  0x00007f58870ffe72 in debugmsg_hex (token=token@entry=0x7f58878a941e "dumpx_recv", thedata=thedata@entry=0x5574809d5cf0 "@", len=len@entry=4) at snmp_debug.c:557
#6  0x00007f588789730e in agentx_parse_int (data=0x5574809d5cf0 "@", network_byte_order=0) at mibgroup/agentx/protocol.c:1070
#7  0x00007f588789b9b8 in agentx_check_packet (packet=<optimized out>, packet_len=<optimized out>) at mibgroup/agentx/protocol.c:2129
#8  0x00007f58870ea4d9 in _sess_read (sessp=sessp@entry=0x5574809978a0, fdset=fdset@entry=0x7ffe5ec94f80) at snmp_api.c:6242
#9  0x00007f58870eb259 in snmp_sess_read2 (sessp=sessp@entry=0x5574809978a0, fdset=fdset@entry=0x7ffe5ec94f80) at snmp_api.c:6415
#10 0x00007f58870eb2ab in snmp_read2 (fdset=0x7ffe5ec94f80) at snmp_api.c:5930
#11 0x000055747ec8504c in receive () at snmpd.c:1477
#12 0x000055747ec841ac in main (argc=<optimized out>, argv=<optimized out>) at snmpd.c:1227

Thanks again for your suggestions.
