### ISSUE TITLE
[python module] wrong value for OCTETSTR, str instead of bytes

### ISSUE THREAD

**Issue by dbilli** [net-snmp/net-snmp#587]
I think there is a wrong use of STR() in netsnmp/client.py. 

With some OIDS (es: 1.3.6.1.2.1.25.1.2.0 )  the byte-array value (b"....") is "stringified"  ( 'b"...."' )

This is the test:

```
import netsnmp

options = {
	'DestHost'  : 'localhost:161',
	'Community' : 'public',
	'Timeout'   : 3,
	'Retries'   : 3,
	'Version'   : 2,
	'UseNumeric': 1,
}

sess = netsnmp.Session(**options)
 
vb = netsnmp.Varbind('.1.3.6.1.2.1.25.1.2.0') 

vl = netsnmp.VarList(vb)

res = sess.get(vl)

print( vb.iid  )
print( vb.type )
print( type(vb.val)  )
print( repr(vb.val)  )
print( vb.val        )

```

Execution:

```
#################################### TEST 1

>>> import netsnmp
>>> 
>>> options = {
...     'DestHost'  : 'localhost:161',
...     'Community' : 'public',
...     'Timeout'   : 3,
...     'Retries'   : 3,
...     'Version'   : 2,
...     'UseNumeric': 1,
... }
>>> 
>>> sess = netsnmp.Session(**options)
>>>  
>>> vb = netsnmp.Varbind('.1.3.6.1.2.1.25.1.2.0') 
>>> 
>>> vl = netsnmp.VarList(vb)
>>> 
>>> res = sess.get(vl)
>>> 
>>> print( vb.iid  )
0
>>> print( vb.type )
OCTETSTR
>>> print( type(vb.val)  )
<class 'str'>                                                 <-------- WRONG
>>> print( repr(vb.val)  )
"b'\\x07\\xe7\\x05\\x18\\x16\\x13\\x1f\\x00+\\x02\\x00'"      
>>> print( vb.val        )
b'\x07\xe7\x05\x18\x16\x13\x1f\x00+\x02\x00'                  <-------- WRONG
>>> 


This is the patch to avoid the problem.

```
patch ./netsnmp/client.py <<EOF
59c59
<         self.val = STR(val)
---
>         self.val = val
69c69
<         self.__dict__[name] = STR(val)
---
>         self.__dict__[name] = STR(val) if name != 'val' else val
EOF

```

This is the second test:


```
#################################### TEST 2

>>> 
>>> import netsnmp
>>> 
>>> options = {
...     'DestHost'  : 'localhost:161',
...     'Community' : 'public',
...     'Timeout'   : 3,
...     'Retries'   : 3,
...     'Version'   : 2,
...     'UseNumeric': 1,
... }
>>> 
>>> sess = netsnmp.Session(**options)
>>>  
>>> vb = netsnmp.Varbind('.1.3.6.1.2.1.25.1.2.0') 
>>> 
>>> vl = netsnmp.VarList(vb)
>>> 
>>> res = sess.get(vl)
>>> 
>>> print( vb.iid  )
0
>>> print( vb.type )
OCTETSTR
>>> print( type(vb.val)  )
<class 'bytes'>                                               <-------- OK
>>> print( repr(vb.val)  )
b'\x07\xe7\x05\x18\x16\x14\x1f\x00+\x02\x00'
>>> print( vb.val        )
b'\x07\xe7\x05\x18\x16\x14\x1f\x00+\x02\x00'                  <-------- OK
>>> 

```

**Comment by bvanassche** [comment]
The above change causes two unit tests to fail:
```
export NOAUTODEPS=1 &&
make -s &&
export LD_LIBRARY_PATH="$PWD/snmplib/.libs:$PWD/agent/.libs:$PWD/agent/helpers/.libs:" &&
export MIBDIRS="$PWD/mibs" &&
export SNMP_PERSISTENT_DIR=/tmp/net-snmp &&
export SNMP_SNMPD_PORT=1161 &&
export PYTHONPATH="$PWD/python/netsnmp" &&
mkdir -p "$SNMP_PERSISTENT_DIR" &&
{
    agent/snmpd -I-smux -r -f -Lo -c python/netsnmp/tests/snmpd.conf localhost:${SNMP_SNMPD_PORT} &
    pid=$!
} &&
PYTHONPROG=$(sed -n 's/^S\["PYTHONPROG"\]="\(.*\)"$/\1/p' config.status) &&
[ -n "$PYTHONPROG" ] &&
cd python &&
$PYTHONPROG setup.py --basedir="$PWD/.." test &&
kill $pid &&
wait
[ ... ]

======================================================================
ERROR: testFunc (netsnmp.tests.test.HexStringSet)
HexStringSet
----------------------------------------------------------------------
TypeError: bad argument type for built-in operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bart/software/net-snmp/python/netsnmp/tests/test.py", line 593, in testFunc
    res = netsnmp.snmpset(var, **snmp_dest());
  File "/home/bart/software/net-snmp/python/netsnmp/client.py", line 245, in snmpset
    res = sess.set(var_list)
  File "/home/bart/software/net-snmp/python/netsnmp/client.py", line 199, in set
    res = netsnmp.client_intf.set(self, varlist)
SystemError: <built-in function set> returned a result with an exception set

======================================================================
ERROR: testFuncs (netsnmp.tests.test.SetTests)
Test code
----------------------------------------------------------------------
TypeError: bad argument type for built-in operation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bart/software/net-snmp/python/netsnmp/tests/test.py", line 470, in testFuncs
    res = netsnmp.snmpset(var, **snmp_dest())
  File "/home/bart/software/net-snmp/python/netsnmp/client.py", line 245, in snmpset
    res = sess.set(var_list)
  File "/home/bart/software/net-snmp/python/netsnmp/client.py", line 199, in set
    res = netsnmp.client_intf.set(self, varlist)
SystemError: <built-in function set> returned a result with an exception set

----------------------------------------------------------------------
```

**Comment by dbilli** [comment]
> The above change causes two unit tests to fail:
> 

Please don't focus on unit tests for a second.

There is an obvious problem in OCTECTSTR values handling .

If you try this code you can see that the value returned for the OID 1.3.6.1.2.1.25.1.2.0 should be _bytes_ but a wrong _str_  _stringified_  value is returned.

```

import netsnmp

options = {
	'DestHost'  : 'localhost:161',
	'Community' : 'public',
	'Timeout'   : 3,
	'Retries'   : 3,
	'Version'   : 2,
	'UseNumeric': 1,
}

sess = netsnmp.Session(**options)

vb = netsnmp.Varbind('.1.3.6.1.2.1.25.1.2.0') 
vl = netsnmp.VarList(vb)
res = sess.get(vl)
print( "vb.iid  =", vb.iid, type(vb.iid), repr(vb.iid) )
print( "vb.type =", vb.type )
print( "vb.val  =", vb.val, type(vb.val), repr(vb.val)  )
```

OUTPUT

```
vb.iid  = 0 <class 'str'> '0'
vb.type = OCTETSTR
vb.val  = b'\x07\xe7\x05\x19\x05+\x1e\x00+\x02\x00' <class 'str'> "b'\\x07\\xe7\\x05\\x19\\x05+\\x1e\\x00+\\x02\\x00'"
```

in the last line you can see   vb.val  is  not bytes, it's the stringified  version of the real byte array returned by the C library.

This can not be correct.


```
class Varbind(object):
    def __init__(self, tag=None, iid=None, val=None, type_arg=None):
        self.tag = STR(tag)
        self.iid = STR(iid)
-        self.val = STR(val)                   <-------------------------
+        self.val = val                          <-------------------------
        self.type = STR(type_arg)
        # parse iid out of tag if needed
        if iid is None and tag is not None:
            regex = re.compile(r'^((?:\.\d+)+|(?:\w+(?:[-:]*\w+)+))\.?(.*)$')
            match = regex.match(tag)
            if match:
                (self.tag, self.iid) = match.group(1, 2)

    def __setattr__(self, name, val):
-        self.__dict__[name] = STR(val)                                                 <-------------------------
+        self.__dict__[name] = STR(val) if name != 'val' else val        <-------------------------

    def __str__(self):
        return obj_to_str(self)

    def print_str(self):
        return self.tag, self.iid, self.val, self.type
        ```

**Comment by bvanassche** [comment]
Please convert the above patch into a pull request and include fixes for the Python unit tests. The Python unit tests can be run as follows:
```
killall snmpd
export NOAUTODEPS=1 &&
make -s &&
export LD_LIBRARY_PATH="$PWD/snmplib/.libs:$PWD/agent/.libs:$PWD/agent/helpers/.libs:" &&
export MIBDIRS="$PWD/mibs" &&
export SNMP_PERSISTENT_DIR=/tmp/net-snmp &&
export SNMP_SNMPD_PORT=1161 &&
export PYTHONPATH="$PWD/python/netsnmp" &&
mkdir -p "$SNMP_PERSISTENT_DIR" &&
{
    agent/snmpd -I-smux -r -f -Lo -c python/netsnmp/tests/snmpd.conf localhost:${SNMP_SNMPD_PORT} &
    pid=$!
} &&
PYTHONPROG=$(sed -n 's/^S\["PYTHONPROG"\]="\(.*\)"$/\1/p' config.status) &&
[ -n "$PYTHONPROG" ] &&
cd python &&
$PYTHONPROG setup.py --basedir="$PWD/.." test &&
kill $pid &&
wait
```
