### ISSUE TITLE
snmptranslate: Segfault if launched with -Op

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#679]
Launching `snmptranslate -Op` crashes.

```
(gdb) r -Op
Starting program: net-snmp/apps/.libs/lt-snmptranslate -Op

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b2b8bd in snmp_out_options (options=0x7fffffffdce2 "", argc=argc@entry=0, argv=argv@entry=0x0) at mib.c:2276
2276                    options = argv[optind++];
(gdb) bt
#0  0x00007ffff7b2b8bd in snmp_out_options (options=0x7fffffffdce2 "", argc=argc@entry=0, argv=argv@entry=0x0) at mib.c:2276
#1  0x00007ffff7b2ba6d in snmp_out_toggle_options (options=<optimized out>) at mib.c:2330
#2  0x0000000000401b67 in main (argc=2, argv=0x7fffffffd998) at snmptranslate.c:229
```

This appears to be caused by snmp_out_options being called with an `argv` of `NULL` and line 2276 attempted to access it: `options = argv[optind++];`

**Comment by nielsb** [comment]
This was fixed as part of PR #678 that went into the V5-9-patches branch yesterday.

**Comment by moshekaplan** [comment]
I pulled the master branch; is it possible these fixes were never incorporated into the main branch?

**Comment by bvanassche** [comment]
The V5-9-patches branch has been merged into the master branch. Please retest.
