### ISSUE TITLE
snmpd crash happens if agent-x subagent is killed with SIGKILL and started again

### ISSUE THREAD

**Issue by Ymitrofanov** [net-snmp/net-snmp#69]
Hello!
I reproduced snmpd crash on Linux on libnet-snmp 5.8 version.
My process is a subagent which connects to snmpd via AgentX. 3rd party process monitors my process with SNMPGET or SNMPGETNEXT periodically, with 5 minutes time interval.
Crash happens when I kill my process with -9 (SIGKILL), and immediately run my process again.
Issue is not 100% reproducible, but it reproduces quite often.
My process prints on start:
unknown snmp version 193
NET-SNMP version 5.8 AgentX subagent connected
And then snmpd crashes with the following stack trace:
Program received signal SIGABRT, Aborted.
0x00007fac95703207 in raise () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-28.el7.x86_64
(gdb) bt
#0  0x00007fac95703207 in raise () from /usr/lib64/libc.so.6
#1  0x00007fac957048f8 in abort () from /usr/lib64/libc.so.6
#2  0x00007fac95745cc7 in __libc_message () from /usr/lib64/libc.so.6
#3  0x00007fac9574c574 in malloc_printerr () from /usr/lib64/libc.so.6
#4  0x00007fac9574fc90 in _int_malloc () from /usr/lib64/libc.so.6
#5  0x00007fac957527dc in malloc () from /usr/lib64/libc.so.6
#6  0x00007fac9575979a in strdup () from /usr/lib64/libc.so.6
#7  0x00007fac972372a8 in netsnmp_container_find_ct (type_list=type_list@entry=0x7fac97657a80 "ipaddress_addr:access_ipaddress:table_container") at container.c:251
#8  netsnmp_container_find (type=type@entry=0x7fac97657a80 "ipaddress_addr:access_ipaddress:table_container") at container.c:290
#9  0x00007fac9761a154 in netsnmp_access_ipaddress_container_init (flags=flags@entry=1) at ip-mib/data_access/ipaddress_common.c:65
#10 0x00007fac9761a4e7 in netsnmp_access_ipaddress_container_load (container=container@entry=0x0, load_flags=load_flags@entry=4) at ip-mib/data_access/ipaddress_common.c:152
#11 0x00007fac975f4864 in ipAddressTable_container_load (container=0xa832b0) at ip-mib/ipAddressTable/ipAddressTable_data_access.c:371
#12 0x00007fac979be6e0 in _cache_load (cache=0xa823b0) at helpers/cache_handler.c:735
#13 0x00007fac9721739c in run_alarms () at snmp_alarm.c:218
#14 0x000000000040457f in receive () at snmpd.c:1376
#15 0x0000000000403b0d in main (argc=<optimized out>, argv=<optimized out>) at snmpd.c:1125

Thank you for support!

**Comment by bvanassche** [comment]
That sounds like memory corruption. How about starting snmpd under Valgrind to determine the root cause?

**Comment by Ymitrofanov** [comment]
Unfortunately I could not reproduce snmpd crash today running under Valgrind, but anyway I got some errors about invalid reading and deleting. I attached file with VG errors to current issue, please check.
[vg_snmpd.zip](https://github.com/net-snmp/net-snmp/files/4219123/vg_snmpd.zip)

**Comment by bvanassche** [comment]
From that zip file:
```
==5979== Invalid read of size 4
==5979==    at 0x4E60E79: netsnmp_handler_check_cache (agent_handler.c:910)
==5979==    by 0x4E79A84: agentx_got_response (master.c:217)
==5979==    by 0x5564CE7: snmp_resend_request.constprop.9 (snmp_api.c:6747)
==5979==    by 0x5567212: snmp_sess_timeout (snmp_api.c:6826)
==5979==    by 0x5567327: snmp_timeout (snmp_api.c:6660)
==5979==    by 0x404574: receive (snmpd.c:1346)
==5979==    by 0x403B0C: main (snmpd.c:1125)
==5979==  Address 0xa34c760 is 0 bytes inside a block of size 48 free'd
==5979==    at 0x4C2ACBD: free (vg_replace_malloc.c:530)
==5979==    by 0x4E79AD5: agentx_got_response (master.c:292)
==5979==    by 0x5564CE7: snmp_resend_request.constprop.9 (snmp_api.c:6747)
==5979==    by 0x5567212: snmp_sess_timeout (snmp_api.c:6826)
==5979==    by 0x5567327: snmp_timeout (snmp_api.c:6660)
==5979==    by 0x404574: receive (snmpd.c:1346)
==5979==    by 0x403B0C: main (snmpd.c:1125)
==5979==  Block was alloc'd at
==5979==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
==5979==    by 0x4E60E35: netsnmp_create_delegated_cache (agent_handler.c:881)
==5979==    by 0x4E7AF91: agentx_master_handler (master.c:597)
==5979==    by 0x4E5FC0E: netsnmp_call_handler (agent_handler.c:546)
==5979==    by 0x4E5FC0E: netsnmp_call_handlers (agent_handler.c:631)
==5979==    by 0x4E70958: handle_var_requests (snmp_agent.c:3001)
==5979==    by 0x4E71AFE: handle_pdu (snmp_agent.c:3829)
==5979==    by 0x4E71CA7: netsnmp_handle_request (snmp_agent.c:3676)
==5979==    by 0x4E722C1: handle_snmp_packet (snmp_agent.c:2283)
==5979==    by 0x556C100: _sess_process_packet_handle_pdu (snmp_api.c:5804)
==5979==    by 0x556C100: _sess_process_packet (snmp_api.c:5860)
==5979==    by 0x556D55C: _sess_read (snmp_api.c:6121)
==5979==    by 0x556DB28: snmp_sess_read2 (snmp_api.c:6394)
==5979==    by 0x556DB7A: snmp_read2 (snmp_api.c:5909)
```

Could this be a duplicate of [https://sourceforge.net/p/net-snmp/bugs/2943/](https://sourceforge.net/p/net-snmp/bugs/2943/)? If so, please retest with the latest version of the v5.8 branch.

**Comment by Ymitrofanov** [comment]
Yes, I think it can be a duplicate of  https://sourceforge.net/p/net-snmp/bugs/2943, actually  excepting a stack trace which I already attached I've also got the same stack trace in gdb as in 2943 with the same scenario and 'linked' our internal issue to 2943. As I can see in source code of 5.8 which I downloaded in december 2019, it doesn't have a fix for 2943. So, we'll apply a patch and verify it again or maybe we'll wait for the next release of net-snmp, because I found a work around using systemd which just restarts snmpd after fail.

**Comment by bvanassche** [comment]
The code on the v5.8 branch should be stable enough for a production environment. Please consider evaluating the code available from [https://github.com/net-snmp/net-snmp/archive/V5-8-patches.zip](https://github.com/net-snmp/net-snmp/archive/V5-8-patches.zip).
