### ISSUE TITLE
snmpget crashes if launched with "-IS" or "-Is" and no additional argument

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#692]
$ snmpget '-IS'
Segmentation fault (core dumped)
$ snmpget '-Is'
Segmentation fault (core dumped)

Tested on git commit ae4c76dabb7b83a92d5ba7a06b5899059a712a96
```
$ libtool --mode=execute gdb '/home/user/Desktop/net-snmp/apps/snmpget'
gdb$ r -Is
Starting program: /home/user/Desktop/net-snmp/apps/.libs/snmpget -Is
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
-----------------------------------------------------------------------------------------------------------------------[e[1m][regs]
  RAX:[e[0;31m] 0x0000000000000033  RBX:[e[0;31m] 0x00007FFFF73FE2A0  RBP:[e[0;31m] 0x0000000000000033  RSP:[e[0;31m] 0x00007FFFFFFFC8E0  [e[1m][e[0;31m]o d I t S z A P C 
  RDI:[e[0;31m] 0x0000000000000002  RSI:[e[0;31m] 0x00007FFFFFFFDF68  RDX:[e[0;31m] 0x0000000000000032  RCX:[e[0;31m] 0x0000000000000001  RIP:[e[0;31m] 0x00007FFFF72FFAE3
  R8 : 0x0000000000000000  R9 : 0x0000000000000000  R10:[e[0;31m] 0x00007FFFFFFFC9D0  R11:[e[0;31m] 0x00007FFFF7F0C6D0  R12:[e[0;31m] 0x0000000000000002
  R13:[e[0;31m] 0x00007FFFFFFFDF68  R14:[e[0;31m] 0x0000000000000001  R15: 0x0000000000000000
  CS: 0033  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 002B				
-----------------------------------------------------------------------------------------------------------------------[e[1m][code]
=> 0x7ffff72ffae3 <_getopt_internal_r+451>:	cmp    BYTE PTR [r15],0x2d
   0x7ffff72ffae7 <_getopt_internal_r+455>:	jne    0x7ffff72ffb28 <_getopt_internal_r+520>
   0x7ffff72ffae9 <_getopt_internal_r+457>:	cmp    BYTE PTR [r15+0x1],0x2d
   0x7ffff72ffaee <_getopt_internal_r+462>:	jne    0x7ffff72ffb28 <_getopt_internal_r+520>
   0x7ffff72ffaf0 <_getopt_internal_r+464>:	cmp    BYTE PTR [r15+0x2],0x0
   0x7ffff72ffaf5 <_getopt_internal_r+469>:	jne    0x7ffff72ffb28 <_getopt_internal_r+520>
   0x7ffff72ffaf7 <_getopt_internal_r+471>:	mov    eax,DWORD PTR [rbx+0x2c]
   0x7ffff72ffafa <_getopt_internal_r+474>:	mov    edx,DWORD PTR [rbx+0x30]
-----------------------------------------------------------------------------------------------------------------------------
0x00007ffff72ffae3 in _getopt_internal_r (argc=argc@entry=0x2, argv=argv@entry=0x7fffffffdf68, optstring=<optimized out>, optstring@entry=0x7fffffffc9d0 "Y:VhHm:M:O:I:P:D:dv:r:t:c:Z:e:E:n:u:l:x:X:a:A:p:T:-:3:L:s:C:", longopts=longopts@entry=0x0, longind=longind@entry=0x0, long_only=long_only@entry=0x0, d=0x7ffff73fe2a0 <getopt_data>, posixly_correct=0x0) at ./posix/getopt.c:528
528	./posix/getopt.c: No such file or directory.
gdb$ bt
#0  0x00007ffff72ffae3 in _getopt_internal_r (argc=argc@entry=0x2, argv=argv@entry=0x7fffffffdf68, optstring=<optimized out>, optstring@entry=0x7fffffffc9d0 "Y:VhHm:M:O:I:P:D:dv:r:t:c:Z:e:E:n:u:l:x:X:a:A:p:T:-:3:L:s:C:", longopts=longopts@entry=0x0, longind=longind@entry=0x0, long_only=long_only@entry=0x0, d=0x7ffff73fe2a0 <getopt_data>, posixly_correct=0x0) at ./posix/getopt.c:528
#1  0x00007ffff72fff7b in _getopt_internal (argc=argc@entry=0x2, argv=argv@entry=0x7fffffffdf68, optstring=optstring@entry=0x7fffffffc9d0 "Y:VhHm:M:O:I:P:D:dv:r:t:c:Z:e:E:n:u:l:x:X:a:A:p:T:-:3:L:s:C:", longopts=longopts@entry=0x0, longind=longind@entry=0x0, long_only=long_only@entry=0x0, posixly_correct=0x0) at ./posix/getopt.c:712
#2  0x00007ffff72fffc7 in getopt (argc=argc@entry=0x2, argv=argv@entry=0x7fffffffdf68, optstring=optstring@entry=0x7fffffffc9d0 "Y:VhHm:M:O:I:P:D:dv:r:t:c:Z:e:E:n:u:l:x:X:a:A:p:T:-:3:L:s:C:") at ./posix/getopt.c:736
#3  0x00007ffff7eb77b9 in netsnmp_parse_args (argc=0x2, argv=0x7fffffffdf68, session=0x7fffffffd830, localOpts=<optimized out>, proc=0x5555555568a0 <optProc>, flags=0x0) at snmp_parse_args.c:235
#4  0x0000555555555459 in main (argc=0x2, argv=0x7fffffffdf68) at snmpget.c:127
```

**Comment by bvanassche** [comment]
Thank you for having reported this. Does commit 8e8d56b7b947 help?

**Comment by moshekaplan** [comment]
Looks good to me, thanks!

**Comment by moshekaplan** [comment]
Note, this issue was found by fuzzing the command-line arguments with afl-fuzz (AFL++):

AFL_NO_FORKSRV=1 AFL_NO_AFFINITY=1 AFL_PRELOAD="/home/user/Desktop/AFLplusplus/utils/argv_fuzzing/argvfuzz64.so" libtool --mode=execute afl-fuzz -m none -i fuzz_in -o fuzz_snmpget_out -- ./apps/snmpget
