### ISSUE TITLE
snmpget crashes if launched with "-LF0" and no additional argument

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#695]
snmpget crashes if launched with "-LF0" and no additional argument

```
$ apps/snmpget  '-LF0'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==526767==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7ffff5cffae3 bp 0x000000000031 sp 0x7fffffffc4d0 T0)
==526767==The signal is caused by a READ memory access.
==526767==Hint: address points to the zero page.
    #0 0x7ffff5cffae3 in _getopt_internal_r posix/getopt.c:528
    #1 0x7ffff5cfff7a in _getopt_internal posix/getopt.c:712
    #2 0x7ffff5cfffc6 in getopt posix/getopt.c:736
    #3 0x7ffff718a305 in netsnmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:235
    #4 0x7ffff718c196 in snmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:695
    #5 0x555555558bf0 in main /home/user/Desktop/net-snmp_asan/apps/snmpget.c:127
    #6 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #7 0x7ffff5c23b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #8 0x555555558524 in _start (/home/user/Desktop/net-snmp_asan/apps/.libs/snmpget+0x4524) (BuildId: c2ca5c43e0cd1079c2c8828dfb7ad4725416cf5e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV posix/getopt.c:528 in _getopt_internal_r
==526767==ABORTING
```

**Comment by bvanassche** [comment]
Is commit b86b92eaaf7840af3079a82ef53c19880c93ad58 sufficient to fix this issue?

**Comment by moshekaplan** [comment]
Looks good to me, thanks!

**Comment by moshekaplan** [comment]
Note, this issue was found by fuzzing the command-line arguments with afl-fuzz (AFL++):

`AFL_NO_FORKSRV=1 AFL_NO_AFFINITY=1 AFL_PRELOAD="/home/user/Desktop/AFLplusplus/utils/argv_fuzzing/argvfuzz64.so" libtool --mode=execute afl-fuzz -m none -i fuzz_in -o fuzz_snmpget_out -- ./apps/snmpget`
