### ISSUE TITLE
double-free in snmplib/snmp_api.c:1964

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#698]
Note: This appears to be very similar to #697

```
$ apps/snmpget '-3k' '' '' '' 
MIB search path: /home/user/.snmp/mibs:/usr/local/share/snmp/mibs
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (IP-MIB): At line 0 in (none)
Cannot find module (TCP-MIB): At line 0 in (none)
Cannot find module (UDP-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-SCHEDULE-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (SNMP-TARGET-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-TYPES): At line 0 in (none)
Cannot find module (SNMP-FRAMEWORK-MIB): At line 0 in (none)
Cannot find module (SNMP-MPD-MIB): At line 0 in (none)
Cannot find module (SNMP-USER-BASED-SM-MIB): At line 0 in (none)
Cannot find module (SNMP-VIEW-BASED-ACM-MIB): At line 0 in (none)
Cannot find module (SNMP-COMMUNITY-MIB): At line 0 in (none)
Cannot find module (IPV6-ICMP-MIB): At line 0 in (none)
Cannot find module (IPV6-MIB): At line 0 in (none)
Cannot find module (IPV6-TCP-MIB): At line 0 in (none)
Cannot find module (IPV6-UDP-MIB): At line 0 in (none)
Cannot find module (IP-FORWARD-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-PASS-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-EXTEND-MIB): At line 0 in (none)
Cannot find module (UCD-DLMOD-MIB): At line 0 in (none)
Cannot find module (SNMP-NOTIFICATION-MIB): At line 0 in (none)
Cannot find module (SNMPv2-TM): At line 0 in (none)
Cannot find module (NET-SNMP-VACM-MIB): At line 0 in (none)
: Unknown Object Identifier (Sub-id not found: (top) -> )
=================================================================
==2208495==ERROR: AddressSanitizer: attempting double-free on 0x603000000190 in thread T0:
    #0 0x7ffff78ddb30 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
    #1 0x7ffff7123ea5 in netsnmp_cleanup_session /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:1964
    #2 0x555555559d14 in main /home/user/Desktop/net-snmp_asan/apps/snmpget.c:254
    #3 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #4 0x7ffff5c23b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #5 0x555555558524 in _start (/home/user/Desktop/net-snmp_asan/apps/.libs/snmpget+0x4524) (BuildId: c2ca5c43e0cd1079c2c8828dfb7ad4725416cf5e)

0x603000000190 is located 0 bytes inside of 32-byte region [0x603000000190,0x6030000001b0)
freed by thread T0 here:
    #0 0x7ffff78ddb30 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
    #1 0x7ffff7123ea5 in netsnmp_cleanup_session /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:1964
    #2 0x7ffff71245b9 in snmp_free_session /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:1984
    #3 0x7ffff7125427 in snmp_sess_close /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:2075
    #4 0x7ffff7125729 in snmp_close /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:2105
    #5 0x555555559d02 in main /home/user/Desktop/net-snmp_asan/apps/snmpget.c:251
    #6 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

previously allocated by thread T0 here:
    #0 0x7ffff78defef in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7ffff71cee14 in snmpv3_parse_arg /home/user/Desktop/net-snmp_asan/snmplib/snmpv3.c:356
    #2 0x7ffff71cfcb4 in snmpv3_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmpv3.c:436
    #3 0x7ffff718a190 in netsnmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:444
    #4 0x7ffff718c1e1 in snmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:695
    #5 0x555555558bf0 in main /home/user/Desktop/net-snmp_asan/apps/snmpget.c:127
    #6 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: double-free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52 in __interceptor_free
==2208495==ABORTING
```

**Comment by moshekaplan** [comment]
Note, this issue was found by fuzzing the command-line arguments with afl-fuzz (AFL++):

`AFL_NO_FORKSRV=1 AFL_NO_AFFINITY=1 AFL_PRELOAD="/home/user/Desktop/AFLplusplus/utils/argv_fuzzing/argvfuzz64.so" libtool --mode=execute afl-fuzz -m none -i fuzz_in -o fuzz_snmpget_out -- ./apps/snmpget`

**Comment by moshekaplan** [comment]
Issue is no longer present; closing
