### ISSUE TITLE
Out of bounds read: snmplib/read_config.c:1789

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#699]
Tested on git commit https://github.com/net-snmp/net-snmp/commit/13622d11459454bf435bc8afeaacb6a740ddf6cf

```
$ 'apps/snmpget' '-YA'
=================================================================
==2209444==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000007f2 at pc 0x7ffff71adbe6 bp 0x7fffffffbf30 sp 0x7fffffffbf20
READ of size 1 at 0x6020000007f2 thread T0
    #0 0x7ffff71adbe5 in skip_white_const /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:1789
    #1 0x7ffff71adb3f in skip_white /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:1781
    #2 0x7ffff71a7063 in snmp_config_when /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:633
    #3 0x7ffff71a7b4e in netsnmp_config_process_memory_list /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:697
    #4 0x7ffff71a7c63 in netsnmp_config_process_memories_when /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:725
    #5 0x7ffff71aa848 in read_premib_configs /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:1100
    #6 0x7ffff711854f in init_snmp /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:925
    #7 0x7ffff718a50e in netsnmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:503
    #8 0x7ffff718c1e1 in snmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:695
    #9 0x555555558bf0 in main /home/user/Desktop/net-snmp_asan/apps/snmpget.c:127
    #10 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #11 0x7ffff5c23b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #12 0x555555558524 in _start (/home/user/Desktop/net-snmp_asan/apps/.libs/snmpget+0x4524) (BuildId: c2ca5c43e0cd1079c2c8828dfb7ad4725416cf5e)

0x6020000007f2 is located 0 bytes after 2-byte region [0x6020000007f0,0x6020000007f2)
allocated by thread T0 here:
    #0 0x7ffff78841b8 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7ffff71a74b7 in netsnmp_config_remember_in_list /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:667
    #2 0x7ffff71a7c13 in netsnmp_config_remember /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:713
    #3 0x7ffff7188a3e in netsnmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:270
    #4 0x7ffff718c1e1 in snmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:695
    #5 0x555555558bf0 in main /home/user/Desktop/net-snmp_asan/apps/snmpget.c:127
    #6 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/user/Desktop/net-snmp_asan/snmplib/read_config.c:1789 in skip_white_const
Shadow bytes around the buggy address:
  0x602000000500: fa fa 07 fa fa fa 00 01 fa fa 04 fa fa fa 05 fa
  0x602000000580: fa fa 00 01 fa fa 04 fa fa fa 05 fa fa fa 00 01
  0x602000000600: fa fa 05 fa fa fa 05 fa fa fa 00 01 fa fa 05 fa
  0x602000000680: fa fa 05 fa fa fa 00 01 fa fa 00 fa fa fa 07 fa
  0x602000000700: fa fa 00 01 fa fa 07 fa fa fa 07 fa fa fa 00 01
=>0x602000000780: fa fa 04 fa fa fa 07 fa fa fa 00 00 fa fa[02]fa
  0x602000000800: fa fa 00 fa fa fa fd fa fa fa 00 04 fa fa 00 04
  0x602000000880: fa fa 00 04 fa fa 06 fa fa fa 00 04 fa fa 00 06
  0x602000000900: fa fa 00 07 fa fa 00 05 fa fa 05 fa fa fa 05 fa
  0x602000000980: fa fa 05 fa fa fa 00 00 fa fa 00 04 fa fa 00 07
  0x602000000a00: fa fa 00 fa fa fa 07 fa fa fa 05 fa fa fa 00 05
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2209444==ABORTING
```

**Comment by moshekaplan** [comment]
Note, this issue was found by fuzzing the command-line arguments with afl-fuzz (AFL++):

`AFL_NO_FORKSRV=1 AFL_NO_AFFINITY=1 AFL_PRELOAD="/home/user/Desktop/AFLplusplus/utils/argv_fuzzing/argvfuzz64.so" libtool --mode=execute afl-fuzz -m none -i fuzz_in -o fuzz_snmpget_out -- ./apps/snmpget`

**Comment by moshekaplan** [comment]
This problem appears to be caused by:
read_config.c:643
643	    line = skip_white(line + (cptr - buf) + strlen(cptr) + 1);

In this case, this is passing `line+2` to `skip_white`, which then causes the first access to go out of bounds

**Comment by moshekaplan** [comment]
Still present. Updated stack trace:

```
$ 'apps/snmpget' '-YA'
=================================================================
==1510525==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5020000007f2 at pc 0x75c63ebb3758 bp 0x7ffce5819cf0 sp 0x7ffce5819ce8
READ of size 1 at 0x5020000007f2 thread T0
    #0 0x75c63ebb3757 in skip_white_const /home/user/Desktop/net-snmp/snmplib/read_config.c:1804:12
    #1 0x75c63eba39e3 in skip_white /home/user/Desktop/net-snmp/snmplib/read_config.c:1796:12
    #2 0x75c63eba39e3 in snmp_config_when /home/user/Desktop/net-snmp/snmplib/read_config.c:643:12
    #3 0x75c63eba75f3 in netsnmp_config_process_memory_list /home/user/Desktop/net-snmp/snmplib/read_config.c:707:9
    #4 0x75c63ebab3ee in netsnmp_config_process_memories_when /home/user/Desktop/net-snmp/snmplib/read_config.c:735:5
    #5 0x75c63ebab3ee in read_premib_configs /home/user/Desktop/net-snmp/snmplib/read_config.c:1115:5
    #6 0x75c63e94d8ee in init_snmp /home/user/Desktop/net-snmp/snmplib/snmp_api.c:925:5
    #7 0x75c63eb22b73 in netsnmp_parse_args /home/user/Desktop/net-snmp/snmplib/snmp_parse_args.c:502:5
    #8 0x5e3a9774f4b9 in main /home/user/Desktop/net-snmp/apps/snmpget.c:127:19
    #9 0x75c63da2a3b7 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #10 0x75c63da2a47a in __libc_start_main csu/../csu/libc-start.c:360:3
    #11 0x5e3a9766d4e4 in _start (/home/user/Desktop/net-snmp/apps/.libs/snmpget+0x2d4e4) (BuildId: 3b67ec34b47eb0e527e0d78ca943c20c5e027b06)

0x5020000007f2 is located 0 bytes after 2-byte region [0x5020000007f0,0x5020000007f2)
allocated by thread T0 here:
    #0 0x5e3a976f4d0e in strdup (/home/user/Desktop/net-snmp/apps/.libs/snmpget+0xb4d0e) (BuildId: 3b67ec34b47eb0e527e0d78ca943c20c5e027b06)
    #1 0x75c63eba4da7 in netsnmp_config_remember_in_list /home/user/Desktop/net-snmp/snmplib/read_config.c:677:28
    #2 0x75c63eb1ebee in netsnmp_parse_args /home/user/Desktop/net-snmp/snmplib/snmp_parse_args.c:270:13
    #3 0x5e3a9774f4b9 in main /home/user/Desktop/net-snmp/apps/snmpget.c:127:19
    #4 0x75c63da2a3b7 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #5 0x75c63da2a47a in __libc_start_main csu/../csu/libc-start.c:360:3
    #6 0x5e3a9766d4e4 in _start (/home/user/Desktop/net-snmp/apps/.libs/snmpget+0x2d4e4) (BuildId: 3b67ec34b47eb0e527e0d78ca943c20c5e027b06)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/user/Desktop/net-snmp/snmplib/read_config.c:1804:12 in skip_white_const
Shadow bytes around the buggy address:
  0x502000000500: fa fa 07 fa fa fa 00 01 fa fa 04 fa fa fa 05 fa
  0x502000000580: fa fa 00 01 fa fa 04 fa fa fa 05 fa fa fa 00 01
  0x502000000600: fa fa 05 fa fa fa 05 fa fa fa 00 01 fa fa 05 fa
  0x502000000680: fa fa 05 fa fa fa 00 01 fa fa 00 fa fa fa 07 fa
  0x502000000700: fa fa 00 01 fa fa 07 fa fa fa 07 fa fa fa 00 01
=>0x502000000780: fa fa 04 fa fa fa 07 fa fa fa 00 00 fa fa[02]fa
  0x502000000800: fa fa 00 fa fa fa fd fa fa fa 00 04 fa fa 00 04
  0x502000000880: fa fa 00 04 fa fa 06 fa fa fa 00 04 fa fa 00 06
  0x502000000900: fa fa 00 07 fa fa 00 05 fa fa 05 fa fa fa 05 fa
  0x502000000980: fa fa 05 fa fa fa 00 00 fa fa 00 04 fa fa 00 07
  0x502000000a00: fa fa 00 fa fa fa 07 fa fa fa 05 fa fa fa 00 05
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1510525==ABORTING
```

**Comment by moshekaplan** [comment]
This issue appears to have been fixed. Closing.
