### ISSUE TITLE
Memory leak when parsing arguments in snmplib/snmp_api.c:7963

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#700]
Tested on 13622d11459454bf435bc8afeaacb6a740ddf6cf

```
$ '/home/user/Desktop/net-snmp_asan/apps/snmpget' '' '-xd' 'A' '-xd' 'B'
MIB search path: /home/user/.snmp/mibs:/usr/local/share/snmp/mibs
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (IP-MIB): At line 0 in (none)
Cannot find module (TCP-MIB): At line 0 in (none)
Cannot find module (UDP-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-SCHEDULE-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (SNMP-TARGET-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-TYPES): At line 0 in (none)
Cannot find module (SNMP-FRAMEWORK-MIB): At line 0 in (none)
Cannot find module (SNMP-MPD-MIB): At line 0 in (none)
Cannot find module (SNMP-USER-BASED-SM-MIB): At line 0 in (none)
Cannot find module (SNMP-VIEW-BASED-ACM-MIB): At line 0 in (none)
Cannot find module (SNMP-COMMUNITY-MIB): At line 0 in (none)
Cannot find module (IPV6-ICMP-MIB): At line 0 in (none)
Cannot find module (IPV6-MIB): At line 0 in (none)
Cannot find module (IPV6-TCP-MIB): At line 0 in (none)
Cannot find module (IPV6-UDP-MIB): At line 0 in (none)
Cannot find module (IP-FORWARD-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-PASS-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-EXTEND-MIB): At line 0 in (none)
Cannot find module (UCD-DLMOD-MIB): At line 0 in (none)
Cannot find module (SNMP-NOTIFICATION-MIB): At line 0 in (none)
Cannot find module (SNMPv2-TM): At line 0 in (none)
Cannot find module (NET-SNMP-VACM-MIB): At line 0 in (none)
A: Unknown Object Identifier (Sub-id not found: (top) -> A)
B: Unknown Object Identifier (Sub-id not found: (top) -> B)

=================================================================
==2210262==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7ffff78defef in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7ffff7163e90 in snmp_duplicate_objid /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:7963
    #2 0x7ffff71ce2c0 in snmpv3_parse_arg /home/user/Desktop/net-snmp_asan/snmplib/snmpv3.c:297
    #3 0x7ffff718a26b in netsnmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:472
    #4 0x7ffff718c1e1 in snmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:695
    #5 0x555555558bf0 in main /home/user/Desktop/net-snmp_asan/apps/snmpget.c:127
    #6 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 80 byte(s) leaked in 1 allocation(s).
```

**Comment by moshekaplan** [comment]
Note, this issue was found by fuzzing the command-line arguments with afl-fuzz (AFL++):

`AFL_NO_FORKSRV=1 AFL_NO_AFFINITY=1 AFL_PRELOAD="/home/user/Desktop/AFLplusplus/utils/argv_fuzzing/argvfuzz64.so" libtool --mode=execute afl-fuzz -m none -i fuzz_in -o fuzz_snmpget_out -- ./apps/snmpget`

**Comment by moshekaplan** [comment]
Appears to no longer be present. Closing.
