### ISSUE TITLE
snmptranslate crashes if launched with "-IS" or "-Is" and no additional argument (snmplib/mib.c:2385 and snmplib/mib.c:2396)

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#701]
This may be related to #692 .

```
$ '/home/user/Desktop/net-snmp_asan/apps/snmptranslate' '-Is'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2217414==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7ffff70ba99c bp 0x7fffffffd6e0 sp 0x7fffffffd6a0 T0)
==2217414==The signal is caused by a READ memory access.
==2217414==Hint: address points to the zero page.
    #0 0x7ffff70ba99c in snmp_in_options /home/user/Desktop/net-snmp_asan/snmplib/mib.c:2385
    #1 0x7ffff70bac37 in snmp_in_toggle_options /home/user/Desktop/net-snmp_asan/snmplib/mib.c:2419
    #2 0x55555555b05c in main /home/user/Desktop/net-snmp_asan/apps/snmptranslate.c:238
    #3 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #4 0x7ffff5c23b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #5 0x5555555598c4 in _start (/home/user/Desktop/net-snmp_asan/apps/.libs/snmptranslate+0x58c4) (BuildId: dd3b21b8eb88a83b2e7418a9e1419095aa69d651)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/user/Desktop/net-snmp_asan/snmplib/mib.c:2385 in snmp_in_options
==2217414==ABORTING
```

```
$ '/home/user/Desktop/net-snmp_asan/apps/snmptranslate'  '-IS'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==2217793==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7ffff70bab3d bp 0x7fffffffd6e0 sp 0x7fffffffd6a0 T0)
==2217793==The signal is caused by a READ memory access.
==2217793==Hint: address points to the zero page.
    #0 0x7ffff70bab3d in snmp_in_options /home/user/Desktop/net-snmp_asan/snmplib/mib.c:2396
    #1 0x7ffff70bac37 in snmp_in_toggle_options /home/user/Desktop/net-snmp_asan/snmplib/mib.c:2419
    #2 0x55555555b05c in main /home/user/Desktop/net-snmp_asan/apps/snmptranslate.c:238
    #3 0x7ffff5c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #4 0x7ffff5c23b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #5 0x5555555598c4 in _start (/home/user/Desktop/net-snmp_asan/apps/.libs/snmptranslate+0x58c4) (BuildId: dd3b21b8eb88a83b2e7418a9e1419095aa69d651)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/user/Desktop/net-snmp_asan/snmplib/mib.c:2396 in snmp_in_options
==2217793==ABORTING
```

**Comment by moshekaplan** [comment]
This bug is caused by `mib.c`'s `snmp_in_toggle_options` calling `snmp_in_options(char *optarg, int argc, char *const *argv)` with `snmp_in_options( options, 0, NULL )` , so `argv` is `NULL`. Therefore, `case 's'` and `case 'S'` which both access `cp = argv[optind++];` trigger a null dereference.

**Comment by moshekaplan** [comment]
Note, this issue was found by fuzzing the command-line arguments with afl-fuzz (AFL++):

`AFL_NO_FORKSRV=1 AFL_NO_AFFINITY=1 AFL_PRELOAD="/home/user/Desktop/AFLplusplus/utils/argv_fuzzing/argvfuzz64.so" libtool --mode=execute afl-fuzz -m none -i fuzz_in -o fuzz_snmpget_out -- ./apps/snmpget`

**Comment by moshekaplan** [comment]
This issue appears to have been fixed. Closing.
