### ISSUE TITLE
snmpusm free() invalid pointer

### ISSUE THREAD

**Issue by rms95** [net-snmp/net-snmp#707]
Since commit 21b16eba60245bc84149d338a9700e5915bda292 the following command fails:
```bash
$ snmpusm -r 0 -t 5 -On -Ih -Ir -v 3 -Oe -OU --hexOutputLength=1024 -l authNoPriv -u InitialUser -a MD5 -A InitialUser  localhost:161 passwd -Ca InitialUser InitialUser authNoPrivUser
free(): invalid pointer
Aborted
```

**Comment by moshekaplan** [comment]
Appears to be fixed, but does still include a few small memory leaks:
```
$ ./apps/snmpusm -M mibs/ -r 0 -t 5 -On -Ih -Ir -v 3 -Oe -OU --hexOutputLength=1024 -l authNoPriv -u InitialUser -a MD5 -A InitialUser  localhost:161 passwd -Ca InitialUser InitialUser authNoPrivUser
snmpset: Unknown user name

=================================================================
==196983==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fe05a6defef in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fe059f6240d in snmp_duplicate_objid /home/user/Desktop/net-snmp_asan/snmplib/snmp_api.c:7965
    #2 0x7fe059fcc57d in snmpv3_parse_arg /home/user/Desktop/net-snmp_asan/snmplib/snmpv3.c:275
    #3 0x7fe059f887e8 in netsnmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:472
    #4 0x7fe059f8a75e in snmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:695
    #5 0x5597d17e95cc in main /home/user/Desktop/net-snmp_asan/apps/snmpusm.c:388
    #6 0x7fe058a23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 15 byte(s) in 1 object(s) allocated from:
    #0 0x7fe05a6841b8 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x5597d17e9fb1 in main /home/user/Desktop/net-snmp_asan/apps/snmpusm.c:482
    #2 0x7fe058a23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 14 byte(s) in 1 object(s) allocated from:
    #0 0x7fe05a6841b8 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7fe059f8a043 in netsnmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:634
    #2 0x7fe059f8a75e in snmp_parse_args /home/user/Desktop/net-snmp_asan/snmplib/snmp_parse_args.c:695
    #3 0x5597d17e95cc in main /home/user/Desktop/net-snmp_asan/apps/snmpusm.c:388
    #4 0x7fe058a23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 109 byte(s) leaked in 3 allocation(s).
```

**Comment by moshekaplan** [comment]
This issue appears to no longer be present and does not trigger any memory leaks. Recommend closure.

**Comment by bvanassche** [comment]
Thanks!
